// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: signaling.proto

#include "signaling.pb.h"
#include "signaling.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace signaling {

static const char* SignalingService_method_names[] = {
  "/signaling.SignalingService/SendMessage",
  "/signaling.SignalingService/StreamEvents",
};

std::unique_ptr< SignalingService::Stub> SignalingService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SignalingService::Stub> stub(new SignalingService::Stub(channel, options));
  return stub;
}

SignalingService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SendMessage_(SignalingService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StreamEvents_(SignalingService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::Status SignalingService::Stub::SendMessage(::grpc::ClientContext* context, const ::signaling::ChatMessage& request, ::signaling::MessageAcknowledged* response) {
  return ::grpc::internal::BlockingUnaryCall< ::signaling::ChatMessage, ::signaling::MessageAcknowledged, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendMessage_, context, request, response);
}

void SignalingService::Stub::async::SendMessage(::grpc::ClientContext* context, const ::signaling::ChatMessage* request, ::signaling::MessageAcknowledged* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::signaling::ChatMessage, ::signaling::MessageAcknowledged, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendMessage_, context, request, response, std::move(f));
}

void SignalingService::Stub::async::SendMessage(::grpc::ClientContext* context, const ::signaling::ChatMessage* request, ::signaling::MessageAcknowledged* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendMessage_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::signaling::MessageAcknowledged>* SignalingService::Stub::PrepareAsyncSendMessageRaw(::grpc::ClientContext* context, const ::signaling::ChatMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::signaling::MessageAcknowledged, ::signaling::ChatMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendMessage_, context, request);
}

::grpc::ClientAsyncResponseReader< ::signaling::MessageAcknowledged>* SignalingService::Stub::AsyncSendMessageRaw(::grpc::ClientContext* context, const ::signaling::ChatMessage& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendMessageRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::signaling::ChatMessage>* SignalingService::Stub::StreamEventsRaw(::grpc::ClientContext* context, const ::signaling::UserIdentity& request) {
  return ::grpc::internal::ClientReaderFactory< ::signaling::ChatMessage>::Create(channel_.get(), rpcmethod_StreamEvents_, context, request);
}

void SignalingService::Stub::async::StreamEvents(::grpc::ClientContext* context, const ::signaling::UserIdentity* request, ::grpc::ClientReadReactor< ::signaling::ChatMessage>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::signaling::ChatMessage>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamEvents_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::signaling::ChatMessage>* SignalingService::Stub::AsyncStreamEventsRaw(::grpc::ClientContext* context, const ::signaling::UserIdentity& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::signaling::ChatMessage>::Create(channel_.get(), cq, rpcmethod_StreamEvents_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::signaling::ChatMessage>* SignalingService::Stub::PrepareAsyncStreamEventsRaw(::grpc::ClientContext* context, const ::signaling::UserIdentity& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::signaling::ChatMessage>::Create(channel_.get(), cq, rpcmethod_StreamEvents_, context, request, false, nullptr);
}

SignalingService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SignalingService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SignalingService::Service, ::signaling::ChatMessage, ::signaling::MessageAcknowledged, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SignalingService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::signaling::ChatMessage* req,
             ::signaling::MessageAcknowledged* resp) {
               return service->SendMessage(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SignalingService_method_names[1],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< SignalingService::Service, ::signaling::UserIdentity, ::signaling::ChatMessage>(
          [](SignalingService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::signaling::UserIdentity* req,
             ::grpc::ServerWriter<::signaling::ChatMessage>* writer) {
               return service->StreamEvents(ctx, req, writer);
             }, this)));
}

SignalingService::Service::~Service() {
}

::grpc::Status SignalingService::Service::SendMessage(::grpc::ServerContext* context, const ::signaling::ChatMessage* request, ::signaling::MessageAcknowledged* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SignalingService::Service::StreamEvents(::grpc::ServerContext* context, const ::signaling::UserIdentity* request, ::grpc::ServerWriter< ::signaling::ChatMessage>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace signaling
#include <grpcpp/ports_undef.inc>

