// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: signaling.proto
#ifndef GRPC_signaling_2eproto__INCLUDED
#define GRPC_signaling_2eproto__INCLUDED

#include "signaling.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace signaling {

class SignalingService final {
 public:
  static constexpr char const* service_full_name() {
    return "signaling.SignalingService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SendMessage(::grpc::ClientContext* context, const ::signaling::ChatMessage& request, ::signaling::MessageAcknowledged* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::signaling::MessageAcknowledged>> AsyncSendMessage(::grpc::ClientContext* context, const ::signaling::ChatMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::signaling::MessageAcknowledged>>(AsyncSendMessageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::signaling::MessageAcknowledged>> PrepareAsyncSendMessage(::grpc::ClientContext* context, const ::signaling::ChatMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::signaling::MessageAcknowledged>>(PrepareAsyncSendMessageRaw(context, request, cq));
    }
    // client sends msg, server acknowledges
    std::unique_ptr< ::grpc::ClientReaderInterface< ::signaling::ChatMessage>> StreamEvents(::grpc::ClientContext* context, const ::signaling::UserIdentity& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::signaling::ChatMessage>>(StreamEventsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::signaling::ChatMessage>> AsyncStreamEvents(::grpc::ClientContext* context, const ::signaling::UserIdentity& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::signaling::ChatMessage>>(AsyncStreamEventsRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::signaling::ChatMessage>> PrepareAsyncStreamEvents(::grpc::ClientContext* context, const ::signaling::UserIdentity& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::signaling::ChatMessage>>(PrepareAsyncStreamEventsRaw(context, request, cq));
    }
    // stream messages to user instead of constant req
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SendMessage(::grpc::ClientContext* context, const ::signaling::ChatMessage* request, ::signaling::MessageAcknowledged* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SendMessage(::grpc::ClientContext* context, const ::signaling::ChatMessage* request, ::signaling::MessageAcknowledged* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // client sends msg, server acknowledges
      virtual void StreamEvents(::grpc::ClientContext* context, const ::signaling::UserIdentity* request, ::grpc::ClientReadReactor< ::signaling::ChatMessage>* reactor) = 0;
      // stream messages to user instead of constant req
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::signaling::MessageAcknowledged>* AsyncSendMessageRaw(::grpc::ClientContext* context, const ::signaling::ChatMessage& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::signaling::MessageAcknowledged>* PrepareAsyncSendMessageRaw(::grpc::ClientContext* context, const ::signaling::ChatMessage& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::signaling::ChatMessage>* StreamEventsRaw(::grpc::ClientContext* context, const ::signaling::UserIdentity& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::signaling::ChatMessage>* AsyncStreamEventsRaw(::grpc::ClientContext* context, const ::signaling::UserIdentity& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::signaling::ChatMessage>* PrepareAsyncStreamEventsRaw(::grpc::ClientContext* context, const ::signaling::UserIdentity& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SendMessage(::grpc::ClientContext* context, const ::signaling::ChatMessage& request, ::signaling::MessageAcknowledged* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::signaling::MessageAcknowledged>> AsyncSendMessage(::grpc::ClientContext* context, const ::signaling::ChatMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::signaling::MessageAcknowledged>>(AsyncSendMessageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::signaling::MessageAcknowledged>> PrepareAsyncSendMessage(::grpc::ClientContext* context, const ::signaling::ChatMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::signaling::MessageAcknowledged>>(PrepareAsyncSendMessageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::signaling::ChatMessage>> StreamEvents(::grpc::ClientContext* context, const ::signaling::UserIdentity& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::signaling::ChatMessage>>(StreamEventsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::signaling::ChatMessage>> AsyncStreamEvents(::grpc::ClientContext* context, const ::signaling::UserIdentity& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::signaling::ChatMessage>>(AsyncStreamEventsRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::signaling::ChatMessage>> PrepareAsyncStreamEvents(::grpc::ClientContext* context, const ::signaling::UserIdentity& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::signaling::ChatMessage>>(PrepareAsyncStreamEventsRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SendMessage(::grpc::ClientContext* context, const ::signaling::ChatMessage* request, ::signaling::MessageAcknowledged* response, std::function<void(::grpc::Status)>) override;
      void SendMessage(::grpc::ClientContext* context, const ::signaling::ChatMessage* request, ::signaling::MessageAcknowledged* response, ::grpc::ClientUnaryReactor* reactor) override;
      void StreamEvents(::grpc::ClientContext* context, const ::signaling::UserIdentity* request, ::grpc::ClientReadReactor< ::signaling::ChatMessage>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::signaling::MessageAcknowledged>* AsyncSendMessageRaw(::grpc::ClientContext* context, const ::signaling::ChatMessage& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::signaling::MessageAcknowledged>* PrepareAsyncSendMessageRaw(::grpc::ClientContext* context, const ::signaling::ChatMessage& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::signaling::ChatMessage>* StreamEventsRaw(::grpc::ClientContext* context, const ::signaling::UserIdentity& request) override;
    ::grpc::ClientAsyncReader< ::signaling::ChatMessage>* AsyncStreamEventsRaw(::grpc::ClientContext* context, const ::signaling::UserIdentity& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::signaling::ChatMessage>* PrepareAsyncStreamEventsRaw(::grpc::ClientContext* context, const ::signaling::UserIdentity& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SendMessage_;
    const ::grpc::internal::RpcMethod rpcmethod_StreamEvents_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SendMessage(::grpc::ServerContext* context, const ::signaling::ChatMessage* request, ::signaling::MessageAcknowledged* response);
    // client sends msg, server acknowledges
    virtual ::grpc::Status StreamEvents(::grpc::ServerContext* context, const ::signaling::UserIdentity* request, ::grpc::ServerWriter< ::signaling::ChatMessage>* writer);
    // stream messages to user instead of constant req
  };
  template <class BaseClass>
  class WithAsyncMethod_SendMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SendMessage() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SendMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendMessage(::grpc::ServerContext* /*context*/, const ::signaling::ChatMessage* /*request*/, ::signaling::MessageAcknowledged* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendMessage(::grpc::ServerContext* context, ::signaling::ChatMessage* request, ::grpc::ServerAsyncResponseWriter< ::signaling::MessageAcknowledged>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamEvents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamEvents() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_StreamEvents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamEvents(::grpc::ServerContext* /*context*/, const ::signaling::UserIdentity* /*request*/, ::grpc::ServerWriter< ::signaling::ChatMessage>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamEvents(::grpc::ServerContext* context, ::signaling::UserIdentity* request, ::grpc::ServerAsyncWriter< ::signaling::ChatMessage>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SendMessage<WithAsyncMethod_StreamEvents<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SendMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SendMessage() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::signaling::ChatMessage, ::signaling::MessageAcknowledged>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::signaling::ChatMessage* request, ::signaling::MessageAcknowledged* response) { return this->SendMessage(context, request, response); }));}
    void SetMessageAllocatorFor_SendMessage(
        ::grpc::MessageAllocator< ::signaling::ChatMessage, ::signaling::MessageAcknowledged>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::signaling::ChatMessage, ::signaling::MessageAcknowledged>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SendMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendMessage(::grpc::ServerContext* /*context*/, const ::signaling::ChatMessage* /*request*/, ::signaling::MessageAcknowledged* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendMessage(
      ::grpc::CallbackServerContext* /*context*/, const ::signaling::ChatMessage* /*request*/, ::signaling::MessageAcknowledged* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_StreamEvents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamEvents() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::signaling::UserIdentity, ::signaling::ChatMessage>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::signaling::UserIdentity* request) { return this->StreamEvents(context, request); }));
    }
    ~WithCallbackMethod_StreamEvents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamEvents(::grpc::ServerContext* /*context*/, const ::signaling::UserIdentity* /*request*/, ::grpc::ServerWriter< ::signaling::ChatMessage>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::signaling::ChatMessage>* StreamEvents(
      ::grpc::CallbackServerContext* /*context*/, const ::signaling::UserIdentity* /*request*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SendMessage<WithCallbackMethod_StreamEvents<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SendMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SendMessage() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SendMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendMessage(::grpc::ServerContext* /*context*/, const ::signaling::ChatMessage* /*request*/, ::signaling::MessageAcknowledged* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_StreamEvents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamEvents() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_StreamEvents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamEvents(::grpc::ServerContext* /*context*/, const ::signaling::UserIdentity* /*request*/, ::grpc::ServerWriter< ::signaling::ChatMessage>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SendMessage() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SendMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendMessage(::grpc::ServerContext* /*context*/, const ::signaling::ChatMessage* /*request*/, ::signaling::MessageAcknowledged* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendMessage(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamEvents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamEvents() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_StreamEvents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamEvents(::grpc::ServerContext* /*context*/, const ::signaling::UserIdentity* /*request*/, ::grpc::ServerWriter< ::signaling::ChatMessage>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamEvents(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SendMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SendMessage() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SendMessage(context, request, response); }));
    }
    ~WithRawCallbackMethod_SendMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendMessage(::grpc::ServerContext* /*context*/, const ::signaling::ChatMessage* /*request*/, ::signaling::MessageAcknowledged* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendMessage(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamEvents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamEvents() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->StreamEvents(context, request); }));
    }
    ~WithRawCallbackMethod_StreamEvents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamEvents(::grpc::ServerContext* /*context*/, const ::signaling::UserIdentity* /*request*/, ::grpc::ServerWriter< ::signaling::ChatMessage>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* StreamEvents(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SendMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SendMessage() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::signaling::ChatMessage, ::signaling::MessageAcknowledged>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::signaling::ChatMessage, ::signaling::MessageAcknowledged>* streamer) {
                       return this->StreamedSendMessage(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SendMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SendMessage(::grpc::ServerContext* /*context*/, const ::signaling::ChatMessage* /*request*/, ::signaling::MessageAcknowledged* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSendMessage(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::signaling::ChatMessage,::signaling::MessageAcknowledged>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SendMessage<Service > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_StreamEvents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_StreamEvents() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::signaling::UserIdentity, ::signaling::ChatMessage>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::signaling::UserIdentity, ::signaling::ChatMessage>* streamer) {
                       return this->StreamedStreamEvents(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_StreamEvents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StreamEvents(::grpc::ServerContext* /*context*/, const ::signaling::UserIdentity* /*request*/, ::grpc::ServerWriter< ::signaling::ChatMessage>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedStreamEvents(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::signaling::UserIdentity,::signaling::ChatMessage>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_StreamEvents<Service > SplitStreamedService;
  typedef WithStreamedUnaryMethod_SendMessage<WithSplitStreamingMethod_StreamEvents<Service > > StreamedService;
};

}  // namespace signaling


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_signaling_2eproto__INCLUDED
