// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: sfu_control.proto
#ifndef GRPC_sfu_5fcontrol_2eproto__INCLUDED
#define GRPC_sfu_5fcontrol_2eproto__INCLUDED

#include "sfu_control.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace sfu_control {

class SfuControl final {
 public:
  static constexpr char const* service_full_name() {
    return "sfu_control.SfuControl";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Hand a browser's SDP offer to the SFU. The SFU builds a libdatachannel
    // PeerConnection for (room_id, peer_id), applies the offer, and returns
    // its answer SDP. Idempotent on (room_id, peer_id) — re-calling replaces
    // the previous peer registered under that key.
    virtual ::grpc::Status AddPeer(::grpc::ClientContext* context, const ::sfu_control::AddPeerRequest& request, ::sfu_control::AddPeerResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sfu_control::AddPeerResponse>> AsyncAddPeer(::grpc::ClientContext* context, const ::sfu_control::AddPeerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sfu_control::AddPeerResponse>>(AsyncAddPeerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sfu_control::AddPeerResponse>> PrepareAsyncAddPeer(::grpc::ClientContext* context, const ::sfu_control::AddPeerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sfu_control::AddPeerResponse>>(PrepareAsyncAddPeerRaw(context, request, cq));
    }
    // Tear down a peer connection and drop the peer from its room. If the
    // room becomes empty, RoomRegistry destroys it.
    virtual ::grpc::Status RemovePeer(::grpc::ClientContext* context, const ::sfu_control::RemovePeerRequest& request, ::sfu_control::RemovePeerResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sfu_control::RemovePeerResponse>> AsyncRemovePeer(::grpc::ClientContext* context, const ::sfu_control::RemovePeerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sfu_control::RemovePeerResponse>>(AsyncRemovePeerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sfu_control::RemovePeerResponse>> PrepareAsyncRemovePeer(::grpc::ClientContext* context, const ::sfu_control::RemovePeerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sfu_control::RemovePeerResponse>>(PrepareAsyncRemovePeerRaw(context, request, cq));
    }
    // Trickle a remote (browser-side) ICE candidate into the named peer.
    virtual ::grpc::Status AddRemoteIceCandidate(::grpc::ClientContext* context, const ::sfu_control::AddRemoteIceCandidateRequest& request, ::sfu_control::AddRemoteIceCandidateResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sfu_control::AddRemoteIceCandidateResponse>> AsyncAddRemoteIceCandidate(::grpc::ClientContext* context, const ::sfu_control::AddRemoteIceCandidateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sfu_control::AddRemoteIceCandidateResponse>>(AsyncAddRemoteIceCandidateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sfu_control::AddRemoteIceCandidateResponse>> PrepareAsyncAddRemoteIceCandidate(::grpc::ClientContext* context, const ::sfu_control::AddRemoteIceCandidateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sfu_control::AddRemoteIceCandidateResponse>>(PrepareAsyncAddRemoteIceCandidateRaw(context, request, cq));
    }
    // Server-streaming subscription to events the SFU emits: locally-gathered
    // ICE candidates (which the gateway forwards to the browser as
    // IceCandidate envelopes) and PeerReady when the peer connection reaches
    // Connected. Typically one stream per signaling_server instance for the
    // lifetime of the process.
    std::unique_ptr< ::grpc::ClientReaderInterface< ::sfu_control::PeerEvent>> StreamPeerEvents(::grpc::ClientContext* context, const ::sfu_control::StreamPeerEventsRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::sfu_control::PeerEvent>>(StreamPeerEventsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::sfu_control::PeerEvent>> AsyncStreamPeerEvents(::grpc::ClientContext* context, const ::sfu_control::StreamPeerEventsRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::sfu_control::PeerEvent>>(AsyncStreamPeerEventsRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::sfu_control::PeerEvent>> PrepareAsyncStreamPeerEvents(::grpc::ClientContext* context, const ::sfu_control::StreamPeerEventsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::sfu_control::PeerEvent>>(PrepareAsyncStreamPeerEventsRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Hand a browser's SDP offer to the SFU. The SFU builds a libdatachannel
      // PeerConnection for (room_id, peer_id), applies the offer, and returns
      // its answer SDP. Idempotent on (room_id, peer_id) — re-calling replaces
      // the previous peer registered under that key.
      virtual void AddPeer(::grpc::ClientContext* context, const ::sfu_control::AddPeerRequest* request, ::sfu_control::AddPeerResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AddPeer(::grpc::ClientContext* context, const ::sfu_control::AddPeerRequest* request, ::sfu_control::AddPeerResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Tear down a peer connection and drop the peer from its room. If the
      // room becomes empty, RoomRegistry destroys it.
      virtual void RemovePeer(::grpc::ClientContext* context, const ::sfu_control::RemovePeerRequest* request, ::sfu_control::RemovePeerResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RemovePeer(::grpc::ClientContext* context, const ::sfu_control::RemovePeerRequest* request, ::sfu_control::RemovePeerResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Trickle a remote (browser-side) ICE candidate into the named peer.
      virtual void AddRemoteIceCandidate(::grpc::ClientContext* context, const ::sfu_control::AddRemoteIceCandidateRequest* request, ::sfu_control::AddRemoteIceCandidateResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AddRemoteIceCandidate(::grpc::ClientContext* context, const ::sfu_control::AddRemoteIceCandidateRequest* request, ::sfu_control::AddRemoteIceCandidateResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Server-streaming subscription to events the SFU emits: locally-gathered
      // ICE candidates (which the gateway forwards to the browser as
      // IceCandidate envelopes) and PeerReady when the peer connection reaches
      // Connected. Typically one stream per signaling_server instance for the
      // lifetime of the process.
      virtual void StreamPeerEvents(::grpc::ClientContext* context, const ::sfu_control::StreamPeerEventsRequest* request, ::grpc::ClientReadReactor< ::sfu_control::PeerEvent>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sfu_control::AddPeerResponse>* AsyncAddPeerRaw(::grpc::ClientContext* context, const ::sfu_control::AddPeerRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sfu_control::AddPeerResponse>* PrepareAsyncAddPeerRaw(::grpc::ClientContext* context, const ::sfu_control::AddPeerRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sfu_control::RemovePeerResponse>* AsyncRemovePeerRaw(::grpc::ClientContext* context, const ::sfu_control::RemovePeerRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sfu_control::RemovePeerResponse>* PrepareAsyncRemovePeerRaw(::grpc::ClientContext* context, const ::sfu_control::RemovePeerRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sfu_control::AddRemoteIceCandidateResponse>* AsyncAddRemoteIceCandidateRaw(::grpc::ClientContext* context, const ::sfu_control::AddRemoteIceCandidateRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sfu_control::AddRemoteIceCandidateResponse>* PrepareAsyncAddRemoteIceCandidateRaw(::grpc::ClientContext* context, const ::sfu_control::AddRemoteIceCandidateRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::sfu_control::PeerEvent>* StreamPeerEventsRaw(::grpc::ClientContext* context, const ::sfu_control::StreamPeerEventsRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::sfu_control::PeerEvent>* AsyncStreamPeerEventsRaw(::grpc::ClientContext* context, const ::sfu_control::StreamPeerEventsRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::sfu_control::PeerEvent>* PrepareAsyncStreamPeerEventsRaw(::grpc::ClientContext* context, const ::sfu_control::StreamPeerEventsRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status AddPeer(::grpc::ClientContext* context, const ::sfu_control::AddPeerRequest& request, ::sfu_control::AddPeerResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sfu_control::AddPeerResponse>> AsyncAddPeer(::grpc::ClientContext* context, const ::sfu_control::AddPeerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sfu_control::AddPeerResponse>>(AsyncAddPeerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sfu_control::AddPeerResponse>> PrepareAsyncAddPeer(::grpc::ClientContext* context, const ::sfu_control::AddPeerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sfu_control::AddPeerResponse>>(PrepareAsyncAddPeerRaw(context, request, cq));
    }
    ::grpc::Status RemovePeer(::grpc::ClientContext* context, const ::sfu_control::RemovePeerRequest& request, ::sfu_control::RemovePeerResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sfu_control::RemovePeerResponse>> AsyncRemovePeer(::grpc::ClientContext* context, const ::sfu_control::RemovePeerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sfu_control::RemovePeerResponse>>(AsyncRemovePeerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sfu_control::RemovePeerResponse>> PrepareAsyncRemovePeer(::grpc::ClientContext* context, const ::sfu_control::RemovePeerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sfu_control::RemovePeerResponse>>(PrepareAsyncRemovePeerRaw(context, request, cq));
    }
    ::grpc::Status AddRemoteIceCandidate(::grpc::ClientContext* context, const ::sfu_control::AddRemoteIceCandidateRequest& request, ::sfu_control::AddRemoteIceCandidateResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sfu_control::AddRemoteIceCandidateResponse>> AsyncAddRemoteIceCandidate(::grpc::ClientContext* context, const ::sfu_control::AddRemoteIceCandidateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sfu_control::AddRemoteIceCandidateResponse>>(AsyncAddRemoteIceCandidateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sfu_control::AddRemoteIceCandidateResponse>> PrepareAsyncAddRemoteIceCandidate(::grpc::ClientContext* context, const ::sfu_control::AddRemoteIceCandidateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sfu_control::AddRemoteIceCandidateResponse>>(PrepareAsyncAddRemoteIceCandidateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::sfu_control::PeerEvent>> StreamPeerEvents(::grpc::ClientContext* context, const ::sfu_control::StreamPeerEventsRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::sfu_control::PeerEvent>>(StreamPeerEventsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::sfu_control::PeerEvent>> AsyncStreamPeerEvents(::grpc::ClientContext* context, const ::sfu_control::StreamPeerEventsRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::sfu_control::PeerEvent>>(AsyncStreamPeerEventsRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::sfu_control::PeerEvent>> PrepareAsyncStreamPeerEvents(::grpc::ClientContext* context, const ::sfu_control::StreamPeerEventsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::sfu_control::PeerEvent>>(PrepareAsyncStreamPeerEventsRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void AddPeer(::grpc::ClientContext* context, const ::sfu_control::AddPeerRequest* request, ::sfu_control::AddPeerResponse* response, std::function<void(::grpc::Status)>) override;
      void AddPeer(::grpc::ClientContext* context, const ::sfu_control::AddPeerRequest* request, ::sfu_control::AddPeerResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void RemovePeer(::grpc::ClientContext* context, const ::sfu_control::RemovePeerRequest* request, ::sfu_control::RemovePeerResponse* response, std::function<void(::grpc::Status)>) override;
      void RemovePeer(::grpc::ClientContext* context, const ::sfu_control::RemovePeerRequest* request, ::sfu_control::RemovePeerResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void AddRemoteIceCandidate(::grpc::ClientContext* context, const ::sfu_control::AddRemoteIceCandidateRequest* request, ::sfu_control::AddRemoteIceCandidateResponse* response, std::function<void(::grpc::Status)>) override;
      void AddRemoteIceCandidate(::grpc::ClientContext* context, const ::sfu_control::AddRemoteIceCandidateRequest* request, ::sfu_control::AddRemoteIceCandidateResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void StreamPeerEvents(::grpc::ClientContext* context, const ::sfu_control::StreamPeerEventsRequest* request, ::grpc::ClientReadReactor< ::sfu_control::PeerEvent>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::sfu_control::AddPeerResponse>* AsyncAddPeerRaw(::grpc::ClientContext* context, const ::sfu_control::AddPeerRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::sfu_control::AddPeerResponse>* PrepareAsyncAddPeerRaw(::grpc::ClientContext* context, const ::sfu_control::AddPeerRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::sfu_control::RemovePeerResponse>* AsyncRemovePeerRaw(::grpc::ClientContext* context, const ::sfu_control::RemovePeerRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::sfu_control::RemovePeerResponse>* PrepareAsyncRemovePeerRaw(::grpc::ClientContext* context, const ::sfu_control::RemovePeerRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::sfu_control::AddRemoteIceCandidateResponse>* AsyncAddRemoteIceCandidateRaw(::grpc::ClientContext* context, const ::sfu_control::AddRemoteIceCandidateRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::sfu_control::AddRemoteIceCandidateResponse>* PrepareAsyncAddRemoteIceCandidateRaw(::grpc::ClientContext* context, const ::sfu_control::AddRemoteIceCandidateRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::sfu_control::PeerEvent>* StreamPeerEventsRaw(::grpc::ClientContext* context, const ::sfu_control::StreamPeerEventsRequest& request) override;
    ::grpc::ClientAsyncReader< ::sfu_control::PeerEvent>* AsyncStreamPeerEventsRaw(::grpc::ClientContext* context, const ::sfu_control::StreamPeerEventsRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::sfu_control::PeerEvent>* PrepareAsyncStreamPeerEventsRaw(::grpc::ClientContext* context, const ::sfu_control::StreamPeerEventsRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_AddPeer_;
    const ::grpc::internal::RpcMethod rpcmethod_RemovePeer_;
    const ::grpc::internal::RpcMethod rpcmethod_AddRemoteIceCandidate_;
    const ::grpc::internal::RpcMethod rpcmethod_StreamPeerEvents_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Hand a browser's SDP offer to the SFU. The SFU builds a libdatachannel
    // PeerConnection for (room_id, peer_id), applies the offer, and returns
    // its answer SDP. Idempotent on (room_id, peer_id) — re-calling replaces
    // the previous peer registered under that key.
    virtual ::grpc::Status AddPeer(::grpc::ServerContext* context, const ::sfu_control::AddPeerRequest* request, ::sfu_control::AddPeerResponse* response);
    // Tear down a peer connection and drop the peer from its room. If the
    // room becomes empty, RoomRegistry destroys it.
    virtual ::grpc::Status RemovePeer(::grpc::ServerContext* context, const ::sfu_control::RemovePeerRequest* request, ::sfu_control::RemovePeerResponse* response);
    // Trickle a remote (browser-side) ICE candidate into the named peer.
    virtual ::grpc::Status AddRemoteIceCandidate(::grpc::ServerContext* context, const ::sfu_control::AddRemoteIceCandidateRequest* request, ::sfu_control::AddRemoteIceCandidateResponse* response);
    // Server-streaming subscription to events the SFU emits: locally-gathered
    // ICE candidates (which the gateway forwards to the browser as
    // IceCandidate envelopes) and PeerReady when the peer connection reaches
    // Connected. Typically one stream per signaling_server instance for the
    // lifetime of the process.
    virtual ::grpc::Status StreamPeerEvents(::grpc::ServerContext* context, const ::sfu_control::StreamPeerEventsRequest* request, ::grpc::ServerWriter< ::sfu_control::PeerEvent>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_AddPeer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AddPeer() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_AddPeer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddPeer(::grpc::ServerContext* /*context*/, const ::sfu_control::AddPeerRequest* /*request*/, ::sfu_control::AddPeerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAddPeer(::grpc::ServerContext* context, ::sfu_control::AddPeerRequest* request, ::grpc::ServerAsyncResponseWriter< ::sfu_control::AddPeerResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_RemovePeer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RemovePeer() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_RemovePeer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RemovePeer(::grpc::ServerContext* /*context*/, const ::sfu_control::RemovePeerRequest* /*request*/, ::sfu_control::RemovePeerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRemovePeer(::grpc::ServerContext* context, ::sfu_control::RemovePeerRequest* request, ::grpc::ServerAsyncResponseWriter< ::sfu_control::RemovePeerResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_AddRemoteIceCandidate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AddRemoteIceCandidate() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_AddRemoteIceCandidate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddRemoteIceCandidate(::grpc::ServerContext* /*context*/, const ::sfu_control::AddRemoteIceCandidateRequest* /*request*/, ::sfu_control::AddRemoteIceCandidateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAddRemoteIceCandidate(::grpc::ServerContext* context, ::sfu_control::AddRemoteIceCandidateRequest* request, ::grpc::ServerAsyncResponseWriter< ::sfu_control::AddRemoteIceCandidateResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamPeerEvents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamPeerEvents() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_StreamPeerEvents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamPeerEvents(::grpc::ServerContext* /*context*/, const ::sfu_control::StreamPeerEventsRequest* /*request*/, ::grpc::ServerWriter< ::sfu_control::PeerEvent>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamPeerEvents(::grpc::ServerContext* context, ::sfu_control::StreamPeerEventsRequest* request, ::grpc::ServerAsyncWriter< ::sfu_control::PeerEvent>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(3, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_AddPeer<WithAsyncMethod_RemovePeer<WithAsyncMethod_AddRemoteIceCandidate<WithAsyncMethod_StreamPeerEvents<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_AddPeer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AddPeer() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::sfu_control::AddPeerRequest, ::sfu_control::AddPeerResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::sfu_control::AddPeerRequest* request, ::sfu_control::AddPeerResponse* response) { return this->AddPeer(context, request, response); }));}
    void SetMessageAllocatorFor_AddPeer(
        ::grpc::MessageAllocator< ::sfu_control::AddPeerRequest, ::sfu_control::AddPeerResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::sfu_control::AddPeerRequest, ::sfu_control::AddPeerResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AddPeer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddPeer(::grpc::ServerContext* /*context*/, const ::sfu_control::AddPeerRequest* /*request*/, ::sfu_control::AddPeerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AddPeer(
      ::grpc::CallbackServerContext* /*context*/, const ::sfu_control::AddPeerRequest* /*request*/, ::sfu_control::AddPeerResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_RemovePeer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RemovePeer() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::sfu_control::RemovePeerRequest, ::sfu_control::RemovePeerResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::sfu_control::RemovePeerRequest* request, ::sfu_control::RemovePeerResponse* response) { return this->RemovePeer(context, request, response); }));}
    void SetMessageAllocatorFor_RemovePeer(
        ::grpc::MessageAllocator< ::sfu_control::RemovePeerRequest, ::sfu_control::RemovePeerResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::sfu_control::RemovePeerRequest, ::sfu_control::RemovePeerResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RemovePeer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RemovePeer(::grpc::ServerContext* /*context*/, const ::sfu_control::RemovePeerRequest* /*request*/, ::sfu_control::RemovePeerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RemovePeer(
      ::grpc::CallbackServerContext* /*context*/, const ::sfu_control::RemovePeerRequest* /*request*/, ::sfu_control::RemovePeerResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_AddRemoteIceCandidate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AddRemoteIceCandidate() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::sfu_control::AddRemoteIceCandidateRequest, ::sfu_control::AddRemoteIceCandidateResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::sfu_control::AddRemoteIceCandidateRequest* request, ::sfu_control::AddRemoteIceCandidateResponse* response) { return this->AddRemoteIceCandidate(context, request, response); }));}
    void SetMessageAllocatorFor_AddRemoteIceCandidate(
        ::grpc::MessageAllocator< ::sfu_control::AddRemoteIceCandidateRequest, ::sfu_control::AddRemoteIceCandidateResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::sfu_control::AddRemoteIceCandidateRequest, ::sfu_control::AddRemoteIceCandidateResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AddRemoteIceCandidate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddRemoteIceCandidate(::grpc::ServerContext* /*context*/, const ::sfu_control::AddRemoteIceCandidateRequest* /*request*/, ::sfu_control::AddRemoteIceCandidateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AddRemoteIceCandidate(
      ::grpc::CallbackServerContext* /*context*/, const ::sfu_control::AddRemoteIceCandidateRequest* /*request*/, ::sfu_control::AddRemoteIceCandidateResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_StreamPeerEvents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamPeerEvents() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackServerStreamingHandler< ::sfu_control::StreamPeerEventsRequest, ::sfu_control::PeerEvent>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::sfu_control::StreamPeerEventsRequest* request) { return this->StreamPeerEvents(context, request); }));
    }
    ~WithCallbackMethod_StreamPeerEvents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamPeerEvents(::grpc::ServerContext* /*context*/, const ::sfu_control::StreamPeerEventsRequest* /*request*/, ::grpc::ServerWriter< ::sfu_control::PeerEvent>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::sfu_control::PeerEvent>* StreamPeerEvents(
      ::grpc::CallbackServerContext* /*context*/, const ::sfu_control::StreamPeerEventsRequest* /*request*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_AddPeer<WithCallbackMethod_RemovePeer<WithCallbackMethod_AddRemoteIceCandidate<WithCallbackMethod_StreamPeerEvents<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_AddPeer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AddPeer() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_AddPeer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddPeer(::grpc::ServerContext* /*context*/, const ::sfu_control::AddPeerRequest* /*request*/, ::sfu_control::AddPeerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_RemovePeer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RemovePeer() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_RemovePeer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RemovePeer(::grpc::ServerContext* /*context*/, const ::sfu_control::RemovePeerRequest* /*request*/, ::sfu_control::RemovePeerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_AddRemoteIceCandidate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AddRemoteIceCandidate() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_AddRemoteIceCandidate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddRemoteIceCandidate(::grpc::ServerContext* /*context*/, const ::sfu_control::AddRemoteIceCandidateRequest* /*request*/, ::sfu_control::AddRemoteIceCandidateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_StreamPeerEvents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamPeerEvents() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_StreamPeerEvents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamPeerEvents(::grpc::ServerContext* /*context*/, const ::sfu_control::StreamPeerEventsRequest* /*request*/, ::grpc::ServerWriter< ::sfu_control::PeerEvent>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_AddPeer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AddPeer() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_AddPeer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddPeer(::grpc::ServerContext* /*context*/, const ::sfu_control::AddPeerRequest* /*request*/, ::sfu_control::AddPeerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAddPeer(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_RemovePeer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RemovePeer() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_RemovePeer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RemovePeer(::grpc::ServerContext* /*context*/, const ::sfu_control::RemovePeerRequest* /*request*/, ::sfu_control::RemovePeerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRemovePeer(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_AddRemoteIceCandidate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AddRemoteIceCandidate() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_AddRemoteIceCandidate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddRemoteIceCandidate(::grpc::ServerContext* /*context*/, const ::sfu_control::AddRemoteIceCandidateRequest* /*request*/, ::sfu_control::AddRemoteIceCandidateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAddRemoteIceCandidate(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamPeerEvents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamPeerEvents() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_StreamPeerEvents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamPeerEvents(::grpc::ServerContext* /*context*/, const ::sfu_control::StreamPeerEventsRequest* /*request*/, ::grpc::ServerWriter< ::sfu_control::PeerEvent>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamPeerEvents(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(3, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AddPeer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AddPeer() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AddPeer(context, request, response); }));
    }
    ~WithRawCallbackMethod_AddPeer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddPeer(::grpc::ServerContext* /*context*/, const ::sfu_control::AddPeerRequest* /*request*/, ::sfu_control::AddPeerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AddPeer(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RemovePeer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RemovePeer() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RemovePeer(context, request, response); }));
    }
    ~WithRawCallbackMethod_RemovePeer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RemovePeer(::grpc::ServerContext* /*context*/, const ::sfu_control::RemovePeerRequest* /*request*/, ::sfu_control::RemovePeerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RemovePeer(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AddRemoteIceCandidate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AddRemoteIceCandidate() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AddRemoteIceCandidate(context, request, response); }));
    }
    ~WithRawCallbackMethod_AddRemoteIceCandidate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddRemoteIceCandidate(::grpc::ServerContext* /*context*/, const ::sfu_control::AddRemoteIceCandidateRequest* /*request*/, ::sfu_control::AddRemoteIceCandidateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AddRemoteIceCandidate(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamPeerEvents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamPeerEvents() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->StreamPeerEvents(context, request); }));
    }
    ~WithRawCallbackMethod_StreamPeerEvents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamPeerEvents(::grpc::ServerContext* /*context*/, const ::sfu_control::StreamPeerEventsRequest* /*request*/, ::grpc::ServerWriter< ::sfu_control::PeerEvent>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* StreamPeerEvents(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AddPeer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AddPeer() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::sfu_control::AddPeerRequest, ::sfu_control::AddPeerResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::sfu_control::AddPeerRequest, ::sfu_control::AddPeerResponse>* streamer) {
                       return this->StreamedAddPeer(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AddPeer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AddPeer(::grpc::ServerContext* /*context*/, const ::sfu_control::AddPeerRequest* /*request*/, ::sfu_control::AddPeerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAddPeer(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::sfu_control::AddPeerRequest,::sfu_control::AddPeerResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RemovePeer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RemovePeer() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::sfu_control::RemovePeerRequest, ::sfu_control::RemovePeerResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::sfu_control::RemovePeerRequest, ::sfu_control::RemovePeerResponse>* streamer) {
                       return this->StreamedRemovePeer(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RemovePeer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RemovePeer(::grpc::ServerContext* /*context*/, const ::sfu_control::RemovePeerRequest* /*request*/, ::sfu_control::RemovePeerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRemovePeer(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::sfu_control::RemovePeerRequest,::sfu_control::RemovePeerResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AddRemoteIceCandidate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AddRemoteIceCandidate() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::sfu_control::AddRemoteIceCandidateRequest, ::sfu_control::AddRemoteIceCandidateResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::sfu_control::AddRemoteIceCandidateRequest, ::sfu_control::AddRemoteIceCandidateResponse>* streamer) {
                       return this->StreamedAddRemoteIceCandidate(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AddRemoteIceCandidate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AddRemoteIceCandidate(::grpc::ServerContext* /*context*/, const ::sfu_control::AddRemoteIceCandidateRequest* /*request*/, ::sfu_control::AddRemoteIceCandidateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAddRemoteIceCandidate(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::sfu_control::AddRemoteIceCandidateRequest,::sfu_control::AddRemoteIceCandidateResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_AddPeer<WithStreamedUnaryMethod_RemovePeer<WithStreamedUnaryMethod_AddRemoteIceCandidate<Service > > > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_StreamPeerEvents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_StreamPeerEvents() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::sfu_control::StreamPeerEventsRequest, ::sfu_control::PeerEvent>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::sfu_control::StreamPeerEventsRequest, ::sfu_control::PeerEvent>* streamer) {
                       return this->StreamedStreamPeerEvents(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_StreamPeerEvents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StreamPeerEvents(::grpc::ServerContext* /*context*/, const ::sfu_control::StreamPeerEventsRequest* /*request*/, ::grpc::ServerWriter< ::sfu_control::PeerEvent>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedStreamPeerEvents(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::sfu_control::StreamPeerEventsRequest,::sfu_control::PeerEvent>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_StreamPeerEvents<Service > SplitStreamedService;
  typedef WithStreamedUnaryMethod_AddPeer<WithStreamedUnaryMethod_RemovePeer<WithStreamedUnaryMethod_AddRemoteIceCandidate<WithSplitStreamingMethod_StreamPeerEvents<Service > > > > StreamedService;
};

}  // namespace sfu_control


#endif  // GRPC_sfu_5fcontrol_2eproto__INCLUDED
