// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sfu_control.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_sfu_5fcontrol_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_sfu_5fcontrol_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_bases.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "signaling.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_sfu_5fcontrol_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_sfu_5fcontrol_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_sfu_5fcontrol_2eproto;
namespace sfu_control {
class AddPeerRequest;
struct AddPeerRequestDefaultTypeInternal;
extern AddPeerRequestDefaultTypeInternal _AddPeerRequest_default_instance_;
class AddPeerResponse;
struct AddPeerResponseDefaultTypeInternal;
extern AddPeerResponseDefaultTypeInternal _AddPeerResponse_default_instance_;
class AddRemoteIceCandidateRequest;
struct AddRemoteIceCandidateRequestDefaultTypeInternal;
extern AddRemoteIceCandidateRequestDefaultTypeInternal _AddRemoteIceCandidateRequest_default_instance_;
class AddRemoteIceCandidateResponse;
struct AddRemoteIceCandidateResponseDefaultTypeInternal;
extern AddRemoteIceCandidateResponseDefaultTypeInternal _AddRemoteIceCandidateResponse_default_instance_;
class PeerEvent;
struct PeerEventDefaultTypeInternal;
extern PeerEventDefaultTypeInternal _PeerEvent_default_instance_;
class RemovePeerRequest;
struct RemovePeerRequestDefaultTypeInternal;
extern RemovePeerRequestDefaultTypeInternal _RemovePeerRequest_default_instance_;
class RemovePeerResponse;
struct RemovePeerResponseDefaultTypeInternal;
extern RemovePeerResponseDefaultTypeInternal _RemovePeerResponse_default_instance_;
class StreamPeerEventsRequest;
struct StreamPeerEventsRequestDefaultTypeInternal;
extern StreamPeerEventsRequestDefaultTypeInternal _StreamPeerEventsRequest_default_instance_;
}  // namespace sfu_control
PROTOBUF_NAMESPACE_OPEN
template<> ::sfu_control::AddPeerRequest* Arena::CreateMaybeMessage<::sfu_control::AddPeerRequest>(Arena*);
template<> ::sfu_control::AddPeerResponse* Arena::CreateMaybeMessage<::sfu_control::AddPeerResponse>(Arena*);
template<> ::sfu_control::AddRemoteIceCandidateRequest* Arena::CreateMaybeMessage<::sfu_control::AddRemoteIceCandidateRequest>(Arena*);
template<> ::sfu_control::AddRemoteIceCandidateResponse* Arena::CreateMaybeMessage<::sfu_control::AddRemoteIceCandidateResponse>(Arena*);
template<> ::sfu_control::PeerEvent* Arena::CreateMaybeMessage<::sfu_control::PeerEvent>(Arena*);
template<> ::sfu_control::RemovePeerRequest* Arena::CreateMaybeMessage<::sfu_control::RemovePeerRequest>(Arena*);
template<> ::sfu_control::RemovePeerResponse* Arena::CreateMaybeMessage<::sfu_control::RemovePeerResponse>(Arena*);
template<> ::sfu_control::StreamPeerEventsRequest* Arena::CreateMaybeMessage<::sfu_control::StreamPeerEventsRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace sfu_control {

// ===================================================================

class AddPeerRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sfu_control.AddPeerRequest) */ {
 public:
  inline AddPeerRequest() : AddPeerRequest(nullptr) {}
  ~AddPeerRequest() override;
  explicit PROTOBUF_CONSTEXPR AddPeerRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AddPeerRequest(const AddPeerRequest& from);
  AddPeerRequest(AddPeerRequest&& from) noexcept
    : AddPeerRequest() {
    *this = ::std::move(from);
  }

  inline AddPeerRequest& operator=(const AddPeerRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline AddPeerRequest& operator=(AddPeerRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AddPeerRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const AddPeerRequest* internal_default_instance() {
    return reinterpret_cast<const AddPeerRequest*>(
               &_AddPeerRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AddPeerRequest& a, AddPeerRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(AddPeerRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AddPeerRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AddPeerRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AddPeerRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AddPeerRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AddPeerRequest& from) {
    AddPeerRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AddPeerRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sfu_control.AddPeerRequest";
  }
  protected:
  explicit AddPeerRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRoomIdFieldNumber = 1,
    kPeerIdFieldNumber = 2,
    kOfferFieldNumber = 3,
  };
  // string room_id = 1;
  void clear_room_id();
  const std::string& room_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_room_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_room_id();
  PROTOBUF_NODISCARD std::string* release_room_id();
  void set_allocated_room_id(std::string* room_id);
  private:
  const std::string& _internal_room_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_room_id(const std::string& value);
  std::string* _internal_mutable_room_id();
  public:

  // string peer_id = 2;
  void clear_peer_id();
  const std::string& peer_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_peer_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_peer_id();
  PROTOBUF_NODISCARD std::string* release_peer_id();
  void set_allocated_peer_id(std::string* peer_id);
  private:
  const std::string& _internal_peer_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_peer_id(const std::string& value);
  std::string* _internal_mutable_peer_id();
  public:

  // .signaling.Sdp offer = 3;
  bool has_offer() const;
  private:
  bool _internal_has_offer() const;
  public:
  void clear_offer();
  const ::signaling::Sdp& offer() const;
  PROTOBUF_NODISCARD ::signaling::Sdp* release_offer();
  ::signaling::Sdp* mutable_offer();
  void set_allocated_offer(::signaling::Sdp* offer);
  private:
  const ::signaling::Sdp& _internal_offer() const;
  ::signaling::Sdp* _internal_mutable_offer();
  public:
  void unsafe_arena_set_allocated_offer(
      ::signaling::Sdp* offer);
  ::signaling::Sdp* unsafe_arena_release_offer();

  // @@protoc_insertion_point(class_scope:sfu_control.AddPeerRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr room_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr peer_id_;
    ::signaling::Sdp* offer_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sfu_5fcontrol_2eproto;
};
// -------------------------------------------------------------------

class AddPeerResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sfu_control.AddPeerResponse) */ {
 public:
  inline AddPeerResponse() : AddPeerResponse(nullptr) {}
  ~AddPeerResponse() override;
  explicit PROTOBUF_CONSTEXPR AddPeerResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AddPeerResponse(const AddPeerResponse& from);
  AddPeerResponse(AddPeerResponse&& from) noexcept
    : AddPeerResponse() {
    *this = ::std::move(from);
  }

  inline AddPeerResponse& operator=(const AddPeerResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline AddPeerResponse& operator=(AddPeerResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AddPeerResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const AddPeerResponse* internal_default_instance() {
    return reinterpret_cast<const AddPeerResponse*>(
               &_AddPeerResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(AddPeerResponse& a, AddPeerResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(AddPeerResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AddPeerResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AddPeerResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AddPeerResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AddPeerResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AddPeerResponse& from) {
    AddPeerResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AddPeerResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sfu_control.AddPeerResponse";
  }
  protected:
  explicit AddPeerResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAnswerFieldNumber = 1,
  };
  // .signaling.Sdp answer = 1;
  bool has_answer() const;
  private:
  bool _internal_has_answer() const;
  public:
  void clear_answer();
  const ::signaling::Sdp& answer() const;
  PROTOBUF_NODISCARD ::signaling::Sdp* release_answer();
  ::signaling::Sdp* mutable_answer();
  void set_allocated_answer(::signaling::Sdp* answer);
  private:
  const ::signaling::Sdp& _internal_answer() const;
  ::signaling::Sdp* _internal_mutable_answer();
  public:
  void unsafe_arena_set_allocated_answer(
      ::signaling::Sdp* answer);
  ::signaling::Sdp* unsafe_arena_release_answer();

  // @@protoc_insertion_point(class_scope:sfu_control.AddPeerResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::signaling::Sdp* answer_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sfu_5fcontrol_2eproto;
};
// -------------------------------------------------------------------

class RemovePeerRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sfu_control.RemovePeerRequest) */ {
 public:
  inline RemovePeerRequest() : RemovePeerRequest(nullptr) {}
  ~RemovePeerRequest() override;
  explicit PROTOBUF_CONSTEXPR RemovePeerRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RemovePeerRequest(const RemovePeerRequest& from);
  RemovePeerRequest(RemovePeerRequest&& from) noexcept
    : RemovePeerRequest() {
    *this = ::std::move(from);
  }

  inline RemovePeerRequest& operator=(const RemovePeerRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline RemovePeerRequest& operator=(RemovePeerRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RemovePeerRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const RemovePeerRequest* internal_default_instance() {
    return reinterpret_cast<const RemovePeerRequest*>(
               &_RemovePeerRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(RemovePeerRequest& a, RemovePeerRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(RemovePeerRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RemovePeerRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RemovePeerRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RemovePeerRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RemovePeerRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RemovePeerRequest& from) {
    RemovePeerRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RemovePeerRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sfu_control.RemovePeerRequest";
  }
  protected:
  explicit RemovePeerRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRoomIdFieldNumber = 1,
    kPeerIdFieldNumber = 2,
  };
  // string room_id = 1;
  void clear_room_id();
  const std::string& room_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_room_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_room_id();
  PROTOBUF_NODISCARD std::string* release_room_id();
  void set_allocated_room_id(std::string* room_id);
  private:
  const std::string& _internal_room_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_room_id(const std::string& value);
  std::string* _internal_mutable_room_id();
  public:

  // string peer_id = 2;
  void clear_peer_id();
  const std::string& peer_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_peer_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_peer_id();
  PROTOBUF_NODISCARD std::string* release_peer_id();
  void set_allocated_peer_id(std::string* peer_id);
  private:
  const std::string& _internal_peer_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_peer_id(const std::string& value);
  std::string* _internal_mutable_peer_id();
  public:

  // @@protoc_insertion_point(class_scope:sfu_control.RemovePeerRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr room_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr peer_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sfu_5fcontrol_2eproto;
};
// -------------------------------------------------------------------

class RemovePeerResponse final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:sfu_control.RemovePeerResponse) */ {
 public:
  inline RemovePeerResponse() : RemovePeerResponse(nullptr) {}
  explicit PROTOBUF_CONSTEXPR RemovePeerResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RemovePeerResponse(const RemovePeerResponse& from);
  RemovePeerResponse(RemovePeerResponse&& from) noexcept
    : RemovePeerResponse() {
    *this = ::std::move(from);
  }

  inline RemovePeerResponse& operator=(const RemovePeerResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline RemovePeerResponse& operator=(RemovePeerResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RemovePeerResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const RemovePeerResponse* internal_default_instance() {
    return reinterpret_cast<const RemovePeerResponse*>(
               &_RemovePeerResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(RemovePeerResponse& a, RemovePeerResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(RemovePeerResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RemovePeerResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RemovePeerResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RemovePeerResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const RemovePeerResponse& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const RemovePeerResponse& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sfu_control.RemovePeerResponse";
  }
  protected:
  explicit RemovePeerResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:sfu_control.RemovePeerResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_sfu_5fcontrol_2eproto;
};
// -------------------------------------------------------------------

class AddRemoteIceCandidateRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sfu_control.AddRemoteIceCandidateRequest) */ {
 public:
  inline AddRemoteIceCandidateRequest() : AddRemoteIceCandidateRequest(nullptr) {}
  ~AddRemoteIceCandidateRequest() override;
  explicit PROTOBUF_CONSTEXPR AddRemoteIceCandidateRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AddRemoteIceCandidateRequest(const AddRemoteIceCandidateRequest& from);
  AddRemoteIceCandidateRequest(AddRemoteIceCandidateRequest&& from) noexcept
    : AddRemoteIceCandidateRequest() {
    *this = ::std::move(from);
  }

  inline AddRemoteIceCandidateRequest& operator=(const AddRemoteIceCandidateRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline AddRemoteIceCandidateRequest& operator=(AddRemoteIceCandidateRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AddRemoteIceCandidateRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const AddRemoteIceCandidateRequest* internal_default_instance() {
    return reinterpret_cast<const AddRemoteIceCandidateRequest*>(
               &_AddRemoteIceCandidateRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(AddRemoteIceCandidateRequest& a, AddRemoteIceCandidateRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(AddRemoteIceCandidateRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AddRemoteIceCandidateRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AddRemoteIceCandidateRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AddRemoteIceCandidateRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AddRemoteIceCandidateRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AddRemoteIceCandidateRequest& from) {
    AddRemoteIceCandidateRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AddRemoteIceCandidateRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sfu_control.AddRemoteIceCandidateRequest";
  }
  protected:
  explicit AddRemoteIceCandidateRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRoomIdFieldNumber = 1,
    kPeerIdFieldNumber = 2,
    kCandidateFieldNumber = 3,
  };
  // string room_id = 1;
  void clear_room_id();
  const std::string& room_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_room_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_room_id();
  PROTOBUF_NODISCARD std::string* release_room_id();
  void set_allocated_room_id(std::string* room_id);
  private:
  const std::string& _internal_room_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_room_id(const std::string& value);
  std::string* _internal_mutable_room_id();
  public:

  // string peer_id = 2;
  void clear_peer_id();
  const std::string& peer_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_peer_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_peer_id();
  PROTOBUF_NODISCARD std::string* release_peer_id();
  void set_allocated_peer_id(std::string* peer_id);
  private:
  const std::string& _internal_peer_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_peer_id(const std::string& value);
  std::string* _internal_mutable_peer_id();
  public:

  // .signaling.IceCandidate candidate = 3;
  bool has_candidate() const;
  private:
  bool _internal_has_candidate() const;
  public:
  void clear_candidate();
  const ::signaling::IceCandidate& candidate() const;
  PROTOBUF_NODISCARD ::signaling::IceCandidate* release_candidate();
  ::signaling::IceCandidate* mutable_candidate();
  void set_allocated_candidate(::signaling::IceCandidate* candidate);
  private:
  const ::signaling::IceCandidate& _internal_candidate() const;
  ::signaling::IceCandidate* _internal_mutable_candidate();
  public:
  void unsafe_arena_set_allocated_candidate(
      ::signaling::IceCandidate* candidate);
  ::signaling::IceCandidate* unsafe_arena_release_candidate();

  // @@protoc_insertion_point(class_scope:sfu_control.AddRemoteIceCandidateRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr room_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr peer_id_;
    ::signaling::IceCandidate* candidate_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sfu_5fcontrol_2eproto;
};
// -------------------------------------------------------------------

class AddRemoteIceCandidateResponse final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:sfu_control.AddRemoteIceCandidateResponse) */ {
 public:
  inline AddRemoteIceCandidateResponse() : AddRemoteIceCandidateResponse(nullptr) {}
  explicit PROTOBUF_CONSTEXPR AddRemoteIceCandidateResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AddRemoteIceCandidateResponse(const AddRemoteIceCandidateResponse& from);
  AddRemoteIceCandidateResponse(AddRemoteIceCandidateResponse&& from) noexcept
    : AddRemoteIceCandidateResponse() {
    *this = ::std::move(from);
  }

  inline AddRemoteIceCandidateResponse& operator=(const AddRemoteIceCandidateResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline AddRemoteIceCandidateResponse& operator=(AddRemoteIceCandidateResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AddRemoteIceCandidateResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const AddRemoteIceCandidateResponse* internal_default_instance() {
    return reinterpret_cast<const AddRemoteIceCandidateResponse*>(
               &_AddRemoteIceCandidateResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(AddRemoteIceCandidateResponse& a, AddRemoteIceCandidateResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(AddRemoteIceCandidateResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AddRemoteIceCandidateResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AddRemoteIceCandidateResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AddRemoteIceCandidateResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const AddRemoteIceCandidateResponse& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const AddRemoteIceCandidateResponse& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sfu_control.AddRemoteIceCandidateResponse";
  }
  protected:
  explicit AddRemoteIceCandidateResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:sfu_control.AddRemoteIceCandidateResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_sfu_5fcontrol_2eproto;
};
// -------------------------------------------------------------------

class StreamPeerEventsRequest final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:sfu_control.StreamPeerEventsRequest) */ {
 public:
  inline StreamPeerEventsRequest() : StreamPeerEventsRequest(nullptr) {}
  explicit PROTOBUF_CONSTEXPR StreamPeerEventsRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  StreamPeerEventsRequest(const StreamPeerEventsRequest& from);
  StreamPeerEventsRequest(StreamPeerEventsRequest&& from) noexcept
    : StreamPeerEventsRequest() {
    *this = ::std::move(from);
  }

  inline StreamPeerEventsRequest& operator=(const StreamPeerEventsRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline StreamPeerEventsRequest& operator=(StreamPeerEventsRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StreamPeerEventsRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const StreamPeerEventsRequest* internal_default_instance() {
    return reinterpret_cast<const StreamPeerEventsRequest*>(
               &_StreamPeerEventsRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(StreamPeerEventsRequest& a, StreamPeerEventsRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(StreamPeerEventsRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StreamPeerEventsRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StreamPeerEventsRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<StreamPeerEventsRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const StreamPeerEventsRequest& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const StreamPeerEventsRequest& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sfu_control.StreamPeerEventsRequest";
  }
  protected:
  explicit StreamPeerEventsRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:sfu_control.StreamPeerEventsRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_sfu_5fcontrol_2eproto;
};
// -------------------------------------------------------------------

class PeerEvent final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sfu_control.PeerEvent) */ {
 public:
  inline PeerEvent() : PeerEvent(nullptr) {}
  ~PeerEvent() override;
  explicit PROTOBUF_CONSTEXPR PeerEvent(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PeerEvent(const PeerEvent& from);
  PeerEvent(PeerEvent&& from) noexcept
    : PeerEvent() {
    *this = ::std::move(from);
  }

  inline PeerEvent& operator=(const PeerEvent& from) {
    CopyFrom(from);
    return *this;
  }
  inline PeerEvent& operator=(PeerEvent&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PeerEvent& default_instance() {
    return *internal_default_instance();
  }
  enum EventCase {
    kLocalIceCandidate = 3,
    kPeerReady = 4,
    EVENT_NOT_SET = 0,
  };

  static inline const PeerEvent* internal_default_instance() {
    return reinterpret_cast<const PeerEvent*>(
               &_PeerEvent_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(PeerEvent& a, PeerEvent& b) {
    a.Swap(&b);
  }
  inline void Swap(PeerEvent* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PeerEvent* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PeerEvent* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PeerEvent>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PeerEvent& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PeerEvent& from) {
    PeerEvent::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PeerEvent* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sfu_control.PeerEvent";
  }
  protected:
  explicit PeerEvent(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRoomIdFieldNumber = 1,
    kPeerIdFieldNumber = 2,
    kLocalIceCandidateFieldNumber = 3,
    kPeerReadyFieldNumber = 4,
  };
  // string room_id = 1;
  void clear_room_id();
  const std::string& room_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_room_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_room_id();
  PROTOBUF_NODISCARD std::string* release_room_id();
  void set_allocated_room_id(std::string* room_id);
  private:
  const std::string& _internal_room_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_room_id(const std::string& value);
  std::string* _internal_mutable_room_id();
  public:

  // string peer_id = 2;
  void clear_peer_id();
  const std::string& peer_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_peer_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_peer_id();
  PROTOBUF_NODISCARD std::string* release_peer_id();
  void set_allocated_peer_id(std::string* peer_id);
  private:
  const std::string& _internal_peer_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_peer_id(const std::string& value);
  std::string* _internal_mutable_peer_id();
  public:

  // .signaling.IceCandidate local_ice_candidate = 3;
  bool has_local_ice_candidate() const;
  private:
  bool _internal_has_local_ice_candidate() const;
  public:
  void clear_local_ice_candidate();
  const ::signaling::IceCandidate& local_ice_candidate() const;
  PROTOBUF_NODISCARD ::signaling::IceCandidate* release_local_ice_candidate();
  ::signaling::IceCandidate* mutable_local_ice_candidate();
  void set_allocated_local_ice_candidate(::signaling::IceCandidate* local_ice_candidate);
  private:
  const ::signaling::IceCandidate& _internal_local_ice_candidate() const;
  ::signaling::IceCandidate* _internal_mutable_local_ice_candidate();
  public:
  void unsafe_arena_set_allocated_local_ice_candidate(
      ::signaling::IceCandidate* local_ice_candidate);
  ::signaling::IceCandidate* unsafe_arena_release_local_ice_candidate();

  // bool peer_ready = 4;
  bool has_peer_ready() const;
  private:
  bool _internal_has_peer_ready() const;
  public:
  void clear_peer_ready();
  bool peer_ready() const;
  void set_peer_ready(bool value);
  private:
  bool _internal_peer_ready() const;
  void _internal_set_peer_ready(bool value);
  public:

  void clear_event();
  EventCase event_case() const;
  // @@protoc_insertion_point(class_scope:sfu_control.PeerEvent)
 private:
  class _Internal;
  void set_has_local_ice_candidate();
  void set_has_peer_ready();

  inline bool has_event() const;
  inline void clear_has_event();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr room_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr peer_id_;
    union EventUnion {
      constexpr EventUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::signaling::IceCandidate* local_ice_candidate_;
      bool peer_ready_;
    } event_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sfu_5fcontrol_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AddPeerRequest

// string room_id = 1;
inline void AddPeerRequest::clear_room_id() {
  _impl_.room_id_.ClearToEmpty();
}
inline const std::string& AddPeerRequest::room_id() const {
  // @@protoc_insertion_point(field_get:sfu_control.AddPeerRequest.room_id)
  return _internal_room_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AddPeerRequest::set_room_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.room_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sfu_control.AddPeerRequest.room_id)
}
inline std::string* AddPeerRequest::mutable_room_id() {
  std::string* _s = _internal_mutable_room_id();
  // @@protoc_insertion_point(field_mutable:sfu_control.AddPeerRequest.room_id)
  return _s;
}
inline const std::string& AddPeerRequest::_internal_room_id() const {
  return _impl_.room_id_.Get();
}
inline void AddPeerRequest::_internal_set_room_id(const std::string& value) {
  
  _impl_.room_id_.Set(value, GetArenaForAllocation());
}
inline std::string* AddPeerRequest::_internal_mutable_room_id() {
  
  return _impl_.room_id_.Mutable(GetArenaForAllocation());
}
inline std::string* AddPeerRequest::release_room_id() {
  // @@protoc_insertion_point(field_release:sfu_control.AddPeerRequest.room_id)
  return _impl_.room_id_.Release();
}
inline void AddPeerRequest::set_allocated_room_id(std::string* room_id) {
  if (room_id != nullptr) {
    
  } else {
    
  }
  _impl_.room_id_.SetAllocated(room_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.room_id_.IsDefault()) {
    _impl_.room_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:sfu_control.AddPeerRequest.room_id)
}

// string peer_id = 2;
inline void AddPeerRequest::clear_peer_id() {
  _impl_.peer_id_.ClearToEmpty();
}
inline const std::string& AddPeerRequest::peer_id() const {
  // @@protoc_insertion_point(field_get:sfu_control.AddPeerRequest.peer_id)
  return _internal_peer_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AddPeerRequest::set_peer_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.peer_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sfu_control.AddPeerRequest.peer_id)
}
inline std::string* AddPeerRequest::mutable_peer_id() {
  std::string* _s = _internal_mutable_peer_id();
  // @@protoc_insertion_point(field_mutable:sfu_control.AddPeerRequest.peer_id)
  return _s;
}
inline const std::string& AddPeerRequest::_internal_peer_id() const {
  return _impl_.peer_id_.Get();
}
inline void AddPeerRequest::_internal_set_peer_id(const std::string& value) {
  
  _impl_.peer_id_.Set(value, GetArenaForAllocation());
}
inline std::string* AddPeerRequest::_internal_mutable_peer_id() {
  
  return _impl_.peer_id_.Mutable(GetArenaForAllocation());
}
inline std::string* AddPeerRequest::release_peer_id() {
  // @@protoc_insertion_point(field_release:sfu_control.AddPeerRequest.peer_id)
  return _impl_.peer_id_.Release();
}
inline void AddPeerRequest::set_allocated_peer_id(std::string* peer_id) {
  if (peer_id != nullptr) {
    
  } else {
    
  }
  _impl_.peer_id_.SetAllocated(peer_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.peer_id_.IsDefault()) {
    _impl_.peer_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:sfu_control.AddPeerRequest.peer_id)
}

// .signaling.Sdp offer = 3;
inline bool AddPeerRequest::_internal_has_offer() const {
  return this != internal_default_instance() && _impl_.offer_ != nullptr;
}
inline bool AddPeerRequest::has_offer() const {
  return _internal_has_offer();
}
inline const ::signaling::Sdp& AddPeerRequest::_internal_offer() const {
  const ::signaling::Sdp* p = _impl_.offer_;
  return p != nullptr ? *p : reinterpret_cast<const ::signaling::Sdp&>(
      ::signaling::_Sdp_default_instance_);
}
inline const ::signaling::Sdp& AddPeerRequest::offer() const {
  // @@protoc_insertion_point(field_get:sfu_control.AddPeerRequest.offer)
  return _internal_offer();
}
inline void AddPeerRequest::unsafe_arena_set_allocated_offer(
    ::signaling::Sdp* offer) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.offer_);
  }
  _impl_.offer_ = offer;
  if (offer) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:sfu_control.AddPeerRequest.offer)
}
inline ::signaling::Sdp* AddPeerRequest::release_offer() {
  
  ::signaling::Sdp* temp = _impl_.offer_;
  _impl_.offer_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::signaling::Sdp* AddPeerRequest::unsafe_arena_release_offer() {
  // @@protoc_insertion_point(field_release:sfu_control.AddPeerRequest.offer)
  
  ::signaling::Sdp* temp = _impl_.offer_;
  _impl_.offer_ = nullptr;
  return temp;
}
inline ::signaling::Sdp* AddPeerRequest::_internal_mutable_offer() {
  
  if (_impl_.offer_ == nullptr) {
    auto* p = CreateMaybeMessage<::signaling::Sdp>(GetArenaForAllocation());
    _impl_.offer_ = p;
  }
  return _impl_.offer_;
}
inline ::signaling::Sdp* AddPeerRequest::mutable_offer() {
  ::signaling::Sdp* _msg = _internal_mutable_offer();
  // @@protoc_insertion_point(field_mutable:sfu_control.AddPeerRequest.offer)
  return _msg;
}
inline void AddPeerRequest::set_allocated_offer(::signaling::Sdp* offer) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.offer_);
  }
  if (offer) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(offer));
    if (message_arena != submessage_arena) {
      offer = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, offer, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.offer_ = offer;
  // @@protoc_insertion_point(field_set_allocated:sfu_control.AddPeerRequest.offer)
}

// -------------------------------------------------------------------

// AddPeerResponse

// .signaling.Sdp answer = 1;
inline bool AddPeerResponse::_internal_has_answer() const {
  return this != internal_default_instance() && _impl_.answer_ != nullptr;
}
inline bool AddPeerResponse::has_answer() const {
  return _internal_has_answer();
}
inline const ::signaling::Sdp& AddPeerResponse::_internal_answer() const {
  const ::signaling::Sdp* p = _impl_.answer_;
  return p != nullptr ? *p : reinterpret_cast<const ::signaling::Sdp&>(
      ::signaling::_Sdp_default_instance_);
}
inline const ::signaling::Sdp& AddPeerResponse::answer() const {
  // @@protoc_insertion_point(field_get:sfu_control.AddPeerResponse.answer)
  return _internal_answer();
}
inline void AddPeerResponse::unsafe_arena_set_allocated_answer(
    ::signaling::Sdp* answer) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.answer_);
  }
  _impl_.answer_ = answer;
  if (answer) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:sfu_control.AddPeerResponse.answer)
}
inline ::signaling::Sdp* AddPeerResponse::release_answer() {
  
  ::signaling::Sdp* temp = _impl_.answer_;
  _impl_.answer_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::signaling::Sdp* AddPeerResponse::unsafe_arena_release_answer() {
  // @@protoc_insertion_point(field_release:sfu_control.AddPeerResponse.answer)
  
  ::signaling::Sdp* temp = _impl_.answer_;
  _impl_.answer_ = nullptr;
  return temp;
}
inline ::signaling::Sdp* AddPeerResponse::_internal_mutable_answer() {
  
  if (_impl_.answer_ == nullptr) {
    auto* p = CreateMaybeMessage<::signaling::Sdp>(GetArenaForAllocation());
    _impl_.answer_ = p;
  }
  return _impl_.answer_;
}
inline ::signaling::Sdp* AddPeerResponse::mutable_answer() {
  ::signaling::Sdp* _msg = _internal_mutable_answer();
  // @@protoc_insertion_point(field_mutable:sfu_control.AddPeerResponse.answer)
  return _msg;
}
inline void AddPeerResponse::set_allocated_answer(::signaling::Sdp* answer) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.answer_);
  }
  if (answer) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(answer));
    if (message_arena != submessage_arena) {
      answer = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, answer, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.answer_ = answer;
  // @@protoc_insertion_point(field_set_allocated:sfu_control.AddPeerResponse.answer)
}

// -------------------------------------------------------------------

// RemovePeerRequest

// string room_id = 1;
inline void RemovePeerRequest::clear_room_id() {
  _impl_.room_id_.ClearToEmpty();
}
inline const std::string& RemovePeerRequest::room_id() const {
  // @@protoc_insertion_point(field_get:sfu_control.RemovePeerRequest.room_id)
  return _internal_room_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RemovePeerRequest::set_room_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.room_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sfu_control.RemovePeerRequest.room_id)
}
inline std::string* RemovePeerRequest::mutable_room_id() {
  std::string* _s = _internal_mutable_room_id();
  // @@protoc_insertion_point(field_mutable:sfu_control.RemovePeerRequest.room_id)
  return _s;
}
inline const std::string& RemovePeerRequest::_internal_room_id() const {
  return _impl_.room_id_.Get();
}
inline void RemovePeerRequest::_internal_set_room_id(const std::string& value) {
  
  _impl_.room_id_.Set(value, GetArenaForAllocation());
}
inline std::string* RemovePeerRequest::_internal_mutable_room_id() {
  
  return _impl_.room_id_.Mutable(GetArenaForAllocation());
}
inline std::string* RemovePeerRequest::release_room_id() {
  // @@protoc_insertion_point(field_release:sfu_control.RemovePeerRequest.room_id)
  return _impl_.room_id_.Release();
}
inline void RemovePeerRequest::set_allocated_room_id(std::string* room_id) {
  if (room_id != nullptr) {
    
  } else {
    
  }
  _impl_.room_id_.SetAllocated(room_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.room_id_.IsDefault()) {
    _impl_.room_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:sfu_control.RemovePeerRequest.room_id)
}

// string peer_id = 2;
inline void RemovePeerRequest::clear_peer_id() {
  _impl_.peer_id_.ClearToEmpty();
}
inline const std::string& RemovePeerRequest::peer_id() const {
  // @@protoc_insertion_point(field_get:sfu_control.RemovePeerRequest.peer_id)
  return _internal_peer_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RemovePeerRequest::set_peer_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.peer_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sfu_control.RemovePeerRequest.peer_id)
}
inline std::string* RemovePeerRequest::mutable_peer_id() {
  std::string* _s = _internal_mutable_peer_id();
  // @@protoc_insertion_point(field_mutable:sfu_control.RemovePeerRequest.peer_id)
  return _s;
}
inline const std::string& RemovePeerRequest::_internal_peer_id() const {
  return _impl_.peer_id_.Get();
}
inline void RemovePeerRequest::_internal_set_peer_id(const std::string& value) {
  
  _impl_.peer_id_.Set(value, GetArenaForAllocation());
}
inline std::string* RemovePeerRequest::_internal_mutable_peer_id() {
  
  return _impl_.peer_id_.Mutable(GetArenaForAllocation());
}
inline std::string* RemovePeerRequest::release_peer_id() {
  // @@protoc_insertion_point(field_release:sfu_control.RemovePeerRequest.peer_id)
  return _impl_.peer_id_.Release();
}
inline void RemovePeerRequest::set_allocated_peer_id(std::string* peer_id) {
  if (peer_id != nullptr) {
    
  } else {
    
  }
  _impl_.peer_id_.SetAllocated(peer_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.peer_id_.IsDefault()) {
    _impl_.peer_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:sfu_control.RemovePeerRequest.peer_id)
}

// -------------------------------------------------------------------

// RemovePeerResponse

// -------------------------------------------------------------------

// AddRemoteIceCandidateRequest

// string room_id = 1;
inline void AddRemoteIceCandidateRequest::clear_room_id() {
  _impl_.room_id_.ClearToEmpty();
}
inline const std::string& AddRemoteIceCandidateRequest::room_id() const {
  // @@protoc_insertion_point(field_get:sfu_control.AddRemoteIceCandidateRequest.room_id)
  return _internal_room_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AddRemoteIceCandidateRequest::set_room_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.room_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sfu_control.AddRemoteIceCandidateRequest.room_id)
}
inline std::string* AddRemoteIceCandidateRequest::mutable_room_id() {
  std::string* _s = _internal_mutable_room_id();
  // @@protoc_insertion_point(field_mutable:sfu_control.AddRemoteIceCandidateRequest.room_id)
  return _s;
}
inline const std::string& AddRemoteIceCandidateRequest::_internal_room_id() const {
  return _impl_.room_id_.Get();
}
inline void AddRemoteIceCandidateRequest::_internal_set_room_id(const std::string& value) {
  
  _impl_.room_id_.Set(value, GetArenaForAllocation());
}
inline std::string* AddRemoteIceCandidateRequest::_internal_mutable_room_id() {
  
  return _impl_.room_id_.Mutable(GetArenaForAllocation());
}
inline std::string* AddRemoteIceCandidateRequest::release_room_id() {
  // @@protoc_insertion_point(field_release:sfu_control.AddRemoteIceCandidateRequest.room_id)
  return _impl_.room_id_.Release();
}
inline void AddRemoteIceCandidateRequest::set_allocated_room_id(std::string* room_id) {
  if (room_id != nullptr) {
    
  } else {
    
  }
  _impl_.room_id_.SetAllocated(room_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.room_id_.IsDefault()) {
    _impl_.room_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:sfu_control.AddRemoteIceCandidateRequest.room_id)
}

// string peer_id = 2;
inline void AddRemoteIceCandidateRequest::clear_peer_id() {
  _impl_.peer_id_.ClearToEmpty();
}
inline const std::string& AddRemoteIceCandidateRequest::peer_id() const {
  // @@protoc_insertion_point(field_get:sfu_control.AddRemoteIceCandidateRequest.peer_id)
  return _internal_peer_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AddRemoteIceCandidateRequest::set_peer_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.peer_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sfu_control.AddRemoteIceCandidateRequest.peer_id)
}
inline std::string* AddRemoteIceCandidateRequest::mutable_peer_id() {
  std::string* _s = _internal_mutable_peer_id();
  // @@protoc_insertion_point(field_mutable:sfu_control.AddRemoteIceCandidateRequest.peer_id)
  return _s;
}
inline const std::string& AddRemoteIceCandidateRequest::_internal_peer_id() const {
  return _impl_.peer_id_.Get();
}
inline void AddRemoteIceCandidateRequest::_internal_set_peer_id(const std::string& value) {
  
  _impl_.peer_id_.Set(value, GetArenaForAllocation());
}
inline std::string* AddRemoteIceCandidateRequest::_internal_mutable_peer_id() {
  
  return _impl_.peer_id_.Mutable(GetArenaForAllocation());
}
inline std::string* AddRemoteIceCandidateRequest::release_peer_id() {
  // @@protoc_insertion_point(field_release:sfu_control.AddRemoteIceCandidateRequest.peer_id)
  return _impl_.peer_id_.Release();
}
inline void AddRemoteIceCandidateRequest::set_allocated_peer_id(std::string* peer_id) {
  if (peer_id != nullptr) {
    
  } else {
    
  }
  _impl_.peer_id_.SetAllocated(peer_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.peer_id_.IsDefault()) {
    _impl_.peer_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:sfu_control.AddRemoteIceCandidateRequest.peer_id)
}

// .signaling.IceCandidate candidate = 3;
inline bool AddRemoteIceCandidateRequest::_internal_has_candidate() const {
  return this != internal_default_instance() && _impl_.candidate_ != nullptr;
}
inline bool AddRemoteIceCandidateRequest::has_candidate() const {
  return _internal_has_candidate();
}
inline const ::signaling::IceCandidate& AddRemoteIceCandidateRequest::_internal_candidate() const {
  const ::signaling::IceCandidate* p = _impl_.candidate_;
  return p != nullptr ? *p : reinterpret_cast<const ::signaling::IceCandidate&>(
      ::signaling::_IceCandidate_default_instance_);
}
inline const ::signaling::IceCandidate& AddRemoteIceCandidateRequest::candidate() const {
  // @@protoc_insertion_point(field_get:sfu_control.AddRemoteIceCandidateRequest.candidate)
  return _internal_candidate();
}
inline void AddRemoteIceCandidateRequest::unsafe_arena_set_allocated_candidate(
    ::signaling::IceCandidate* candidate) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.candidate_);
  }
  _impl_.candidate_ = candidate;
  if (candidate) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:sfu_control.AddRemoteIceCandidateRequest.candidate)
}
inline ::signaling::IceCandidate* AddRemoteIceCandidateRequest::release_candidate() {
  
  ::signaling::IceCandidate* temp = _impl_.candidate_;
  _impl_.candidate_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::signaling::IceCandidate* AddRemoteIceCandidateRequest::unsafe_arena_release_candidate() {
  // @@protoc_insertion_point(field_release:sfu_control.AddRemoteIceCandidateRequest.candidate)
  
  ::signaling::IceCandidate* temp = _impl_.candidate_;
  _impl_.candidate_ = nullptr;
  return temp;
}
inline ::signaling::IceCandidate* AddRemoteIceCandidateRequest::_internal_mutable_candidate() {
  
  if (_impl_.candidate_ == nullptr) {
    auto* p = CreateMaybeMessage<::signaling::IceCandidate>(GetArenaForAllocation());
    _impl_.candidate_ = p;
  }
  return _impl_.candidate_;
}
inline ::signaling::IceCandidate* AddRemoteIceCandidateRequest::mutable_candidate() {
  ::signaling::IceCandidate* _msg = _internal_mutable_candidate();
  // @@protoc_insertion_point(field_mutable:sfu_control.AddRemoteIceCandidateRequest.candidate)
  return _msg;
}
inline void AddRemoteIceCandidateRequest::set_allocated_candidate(::signaling::IceCandidate* candidate) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.candidate_);
  }
  if (candidate) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(candidate));
    if (message_arena != submessage_arena) {
      candidate = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, candidate, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.candidate_ = candidate;
  // @@protoc_insertion_point(field_set_allocated:sfu_control.AddRemoteIceCandidateRequest.candidate)
}

// -------------------------------------------------------------------

// AddRemoteIceCandidateResponse

// -------------------------------------------------------------------

// StreamPeerEventsRequest

// -------------------------------------------------------------------

// PeerEvent

// string room_id = 1;
inline void PeerEvent::clear_room_id() {
  _impl_.room_id_.ClearToEmpty();
}
inline const std::string& PeerEvent::room_id() const {
  // @@protoc_insertion_point(field_get:sfu_control.PeerEvent.room_id)
  return _internal_room_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PeerEvent::set_room_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.room_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sfu_control.PeerEvent.room_id)
}
inline std::string* PeerEvent::mutable_room_id() {
  std::string* _s = _internal_mutable_room_id();
  // @@protoc_insertion_point(field_mutable:sfu_control.PeerEvent.room_id)
  return _s;
}
inline const std::string& PeerEvent::_internal_room_id() const {
  return _impl_.room_id_.Get();
}
inline void PeerEvent::_internal_set_room_id(const std::string& value) {
  
  _impl_.room_id_.Set(value, GetArenaForAllocation());
}
inline std::string* PeerEvent::_internal_mutable_room_id() {
  
  return _impl_.room_id_.Mutable(GetArenaForAllocation());
}
inline std::string* PeerEvent::release_room_id() {
  // @@protoc_insertion_point(field_release:sfu_control.PeerEvent.room_id)
  return _impl_.room_id_.Release();
}
inline void PeerEvent::set_allocated_room_id(std::string* room_id) {
  if (room_id != nullptr) {
    
  } else {
    
  }
  _impl_.room_id_.SetAllocated(room_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.room_id_.IsDefault()) {
    _impl_.room_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:sfu_control.PeerEvent.room_id)
}

// string peer_id = 2;
inline void PeerEvent::clear_peer_id() {
  _impl_.peer_id_.ClearToEmpty();
}
inline const std::string& PeerEvent::peer_id() const {
  // @@protoc_insertion_point(field_get:sfu_control.PeerEvent.peer_id)
  return _internal_peer_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PeerEvent::set_peer_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.peer_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sfu_control.PeerEvent.peer_id)
}
inline std::string* PeerEvent::mutable_peer_id() {
  std::string* _s = _internal_mutable_peer_id();
  // @@protoc_insertion_point(field_mutable:sfu_control.PeerEvent.peer_id)
  return _s;
}
inline const std::string& PeerEvent::_internal_peer_id() const {
  return _impl_.peer_id_.Get();
}
inline void PeerEvent::_internal_set_peer_id(const std::string& value) {
  
  _impl_.peer_id_.Set(value, GetArenaForAllocation());
}
inline std::string* PeerEvent::_internal_mutable_peer_id() {
  
  return _impl_.peer_id_.Mutable(GetArenaForAllocation());
}
inline std::string* PeerEvent::release_peer_id() {
  // @@protoc_insertion_point(field_release:sfu_control.PeerEvent.peer_id)
  return _impl_.peer_id_.Release();
}
inline void PeerEvent::set_allocated_peer_id(std::string* peer_id) {
  if (peer_id != nullptr) {
    
  } else {
    
  }
  _impl_.peer_id_.SetAllocated(peer_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.peer_id_.IsDefault()) {
    _impl_.peer_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:sfu_control.PeerEvent.peer_id)
}

// .signaling.IceCandidate local_ice_candidate = 3;
inline bool PeerEvent::_internal_has_local_ice_candidate() const {
  return event_case() == kLocalIceCandidate;
}
inline bool PeerEvent::has_local_ice_candidate() const {
  return _internal_has_local_ice_candidate();
}
inline void PeerEvent::set_has_local_ice_candidate() {
  _impl_._oneof_case_[0] = kLocalIceCandidate;
}
inline ::signaling::IceCandidate* PeerEvent::release_local_ice_candidate() {
  // @@protoc_insertion_point(field_release:sfu_control.PeerEvent.local_ice_candidate)
  if (_internal_has_local_ice_candidate()) {
    clear_has_event();
    ::signaling::IceCandidate* temp = _impl_.event_.local_ice_candidate_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.event_.local_ice_candidate_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::signaling::IceCandidate& PeerEvent::_internal_local_ice_candidate() const {
  return _internal_has_local_ice_candidate()
      ? *_impl_.event_.local_ice_candidate_
      : reinterpret_cast< ::signaling::IceCandidate&>(::signaling::_IceCandidate_default_instance_);
}
inline const ::signaling::IceCandidate& PeerEvent::local_ice_candidate() const {
  // @@protoc_insertion_point(field_get:sfu_control.PeerEvent.local_ice_candidate)
  return _internal_local_ice_candidate();
}
inline ::signaling::IceCandidate* PeerEvent::unsafe_arena_release_local_ice_candidate() {
  // @@protoc_insertion_point(field_unsafe_arena_release:sfu_control.PeerEvent.local_ice_candidate)
  if (_internal_has_local_ice_candidate()) {
    clear_has_event();
    ::signaling::IceCandidate* temp = _impl_.event_.local_ice_candidate_;
    _impl_.event_.local_ice_candidate_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void PeerEvent::unsafe_arena_set_allocated_local_ice_candidate(::signaling::IceCandidate* local_ice_candidate) {
  clear_event();
  if (local_ice_candidate) {
    set_has_local_ice_candidate();
    _impl_.event_.local_ice_candidate_ = local_ice_candidate;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:sfu_control.PeerEvent.local_ice_candidate)
}
inline ::signaling::IceCandidate* PeerEvent::_internal_mutable_local_ice_candidate() {
  if (!_internal_has_local_ice_candidate()) {
    clear_event();
    set_has_local_ice_candidate();
    _impl_.event_.local_ice_candidate_ = CreateMaybeMessage< ::signaling::IceCandidate >(GetArenaForAllocation());
  }
  return _impl_.event_.local_ice_candidate_;
}
inline ::signaling::IceCandidate* PeerEvent::mutable_local_ice_candidate() {
  ::signaling::IceCandidate* _msg = _internal_mutable_local_ice_candidate();
  // @@protoc_insertion_point(field_mutable:sfu_control.PeerEvent.local_ice_candidate)
  return _msg;
}

// bool peer_ready = 4;
inline bool PeerEvent::_internal_has_peer_ready() const {
  return event_case() == kPeerReady;
}
inline bool PeerEvent::has_peer_ready() const {
  return _internal_has_peer_ready();
}
inline void PeerEvent::set_has_peer_ready() {
  _impl_._oneof_case_[0] = kPeerReady;
}
inline void PeerEvent::clear_peer_ready() {
  if (_internal_has_peer_ready()) {
    _impl_.event_.peer_ready_ = false;
    clear_has_event();
  }
}
inline bool PeerEvent::_internal_peer_ready() const {
  if (_internal_has_peer_ready()) {
    return _impl_.event_.peer_ready_;
  }
  return false;
}
inline void PeerEvent::_internal_set_peer_ready(bool value) {
  if (!_internal_has_peer_ready()) {
    clear_event();
    set_has_peer_ready();
  }
  _impl_.event_.peer_ready_ = value;
}
inline bool PeerEvent::peer_ready() const {
  // @@protoc_insertion_point(field_get:sfu_control.PeerEvent.peer_ready)
  return _internal_peer_ready();
}
inline void PeerEvent::set_peer_ready(bool value) {
  _internal_set_peer_ready(value);
  // @@protoc_insertion_point(field_set:sfu_control.PeerEvent.peer_ready)
}

inline bool PeerEvent::has_event() const {
  return event_case() != EVENT_NOT_SET;
}
inline void PeerEvent::clear_has_event() {
  _impl_._oneof_case_[0] = EVENT_NOT_SET;
}
inline PeerEvent::EventCase PeerEvent::event_case() const {
  return PeerEvent::EventCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace sfu_control

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_sfu_5fcontrol_2eproto
