// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: sfu_control.proto

#include "sfu_control.pb.h"
#include "sfu_control.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace sfu_control {

static const char* SfuControl_method_names[] = {
  "/sfu_control.SfuControl/AddPeer",
  "/sfu_control.SfuControl/RemovePeer",
  "/sfu_control.SfuControl/AddRemoteIceCandidate",
  "/sfu_control.SfuControl/StreamPeerEvents",
};

std::unique_ptr< SfuControl::Stub> SfuControl::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SfuControl::Stub> stub(new SfuControl::Stub(channel, options));
  return stub;
}

SfuControl::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_AddPeer_(SfuControl_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RemovePeer_(SfuControl_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_AddRemoteIceCandidate_(SfuControl_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StreamPeerEvents_(SfuControl_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::Status SfuControl::Stub::AddPeer(::grpc::ClientContext* context, const ::sfu_control::AddPeerRequest& request, ::sfu_control::AddPeerResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::sfu_control::AddPeerRequest, ::sfu_control::AddPeerResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AddPeer_, context, request, response);
}

void SfuControl::Stub::async::AddPeer(::grpc::ClientContext* context, const ::sfu_control::AddPeerRequest* request, ::sfu_control::AddPeerResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::sfu_control::AddPeerRequest, ::sfu_control::AddPeerResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddPeer_, context, request, response, std::move(f));
}

void SfuControl::Stub::async::AddPeer(::grpc::ClientContext* context, const ::sfu_control::AddPeerRequest* request, ::sfu_control::AddPeerResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddPeer_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::sfu_control::AddPeerResponse>* SfuControl::Stub::PrepareAsyncAddPeerRaw(::grpc::ClientContext* context, const ::sfu_control::AddPeerRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::sfu_control::AddPeerResponse, ::sfu_control::AddPeerRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AddPeer_, context, request);
}

::grpc::ClientAsyncResponseReader< ::sfu_control::AddPeerResponse>* SfuControl::Stub::AsyncAddPeerRaw(::grpc::ClientContext* context, const ::sfu_control::AddPeerRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAddPeerRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status SfuControl::Stub::RemovePeer(::grpc::ClientContext* context, const ::sfu_control::RemovePeerRequest& request, ::sfu_control::RemovePeerResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::sfu_control::RemovePeerRequest, ::sfu_control::RemovePeerResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RemovePeer_, context, request, response);
}

void SfuControl::Stub::async::RemovePeer(::grpc::ClientContext* context, const ::sfu_control::RemovePeerRequest* request, ::sfu_control::RemovePeerResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::sfu_control::RemovePeerRequest, ::sfu_control::RemovePeerResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RemovePeer_, context, request, response, std::move(f));
}

void SfuControl::Stub::async::RemovePeer(::grpc::ClientContext* context, const ::sfu_control::RemovePeerRequest* request, ::sfu_control::RemovePeerResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RemovePeer_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::sfu_control::RemovePeerResponse>* SfuControl::Stub::PrepareAsyncRemovePeerRaw(::grpc::ClientContext* context, const ::sfu_control::RemovePeerRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::sfu_control::RemovePeerResponse, ::sfu_control::RemovePeerRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RemovePeer_, context, request);
}

::grpc::ClientAsyncResponseReader< ::sfu_control::RemovePeerResponse>* SfuControl::Stub::AsyncRemovePeerRaw(::grpc::ClientContext* context, const ::sfu_control::RemovePeerRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRemovePeerRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status SfuControl::Stub::AddRemoteIceCandidate(::grpc::ClientContext* context, const ::sfu_control::AddRemoteIceCandidateRequest& request, ::sfu_control::AddRemoteIceCandidateResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::sfu_control::AddRemoteIceCandidateRequest, ::sfu_control::AddRemoteIceCandidateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AddRemoteIceCandidate_, context, request, response);
}

void SfuControl::Stub::async::AddRemoteIceCandidate(::grpc::ClientContext* context, const ::sfu_control::AddRemoteIceCandidateRequest* request, ::sfu_control::AddRemoteIceCandidateResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::sfu_control::AddRemoteIceCandidateRequest, ::sfu_control::AddRemoteIceCandidateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddRemoteIceCandidate_, context, request, response, std::move(f));
}

void SfuControl::Stub::async::AddRemoteIceCandidate(::grpc::ClientContext* context, const ::sfu_control::AddRemoteIceCandidateRequest* request, ::sfu_control::AddRemoteIceCandidateResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddRemoteIceCandidate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::sfu_control::AddRemoteIceCandidateResponse>* SfuControl::Stub::PrepareAsyncAddRemoteIceCandidateRaw(::grpc::ClientContext* context, const ::sfu_control::AddRemoteIceCandidateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::sfu_control::AddRemoteIceCandidateResponse, ::sfu_control::AddRemoteIceCandidateRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AddRemoteIceCandidate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::sfu_control::AddRemoteIceCandidateResponse>* SfuControl::Stub::AsyncAddRemoteIceCandidateRaw(::grpc::ClientContext* context, const ::sfu_control::AddRemoteIceCandidateRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAddRemoteIceCandidateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::sfu_control::PeerEvent>* SfuControl::Stub::StreamPeerEventsRaw(::grpc::ClientContext* context, const ::sfu_control::StreamPeerEventsRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::sfu_control::PeerEvent>::Create(channel_.get(), rpcmethod_StreamPeerEvents_, context, request);
}

void SfuControl::Stub::async::StreamPeerEvents(::grpc::ClientContext* context, const ::sfu_control::StreamPeerEventsRequest* request, ::grpc::ClientReadReactor< ::sfu_control::PeerEvent>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::sfu_control::PeerEvent>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamPeerEvents_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::sfu_control::PeerEvent>* SfuControl::Stub::AsyncStreamPeerEventsRaw(::grpc::ClientContext* context, const ::sfu_control::StreamPeerEventsRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::sfu_control::PeerEvent>::Create(channel_.get(), cq, rpcmethod_StreamPeerEvents_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::sfu_control::PeerEvent>* SfuControl::Stub::PrepareAsyncStreamPeerEventsRaw(::grpc::ClientContext* context, const ::sfu_control::StreamPeerEventsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::sfu_control::PeerEvent>::Create(channel_.get(), cq, rpcmethod_StreamPeerEvents_, context, request, false, nullptr);
}

SfuControl::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SfuControl_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SfuControl::Service, ::sfu_control::AddPeerRequest, ::sfu_control::AddPeerResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SfuControl::Service* service,
             ::grpc::ServerContext* ctx,
             const ::sfu_control::AddPeerRequest* req,
             ::sfu_control::AddPeerResponse* resp) {
               return service->AddPeer(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SfuControl_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SfuControl::Service, ::sfu_control::RemovePeerRequest, ::sfu_control::RemovePeerResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SfuControl::Service* service,
             ::grpc::ServerContext* ctx,
             const ::sfu_control::RemovePeerRequest* req,
             ::sfu_control::RemovePeerResponse* resp) {
               return service->RemovePeer(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SfuControl_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SfuControl::Service, ::sfu_control::AddRemoteIceCandidateRequest, ::sfu_control::AddRemoteIceCandidateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SfuControl::Service* service,
             ::grpc::ServerContext* ctx,
             const ::sfu_control::AddRemoteIceCandidateRequest* req,
             ::sfu_control::AddRemoteIceCandidateResponse* resp) {
               return service->AddRemoteIceCandidate(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SfuControl_method_names[3],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< SfuControl::Service, ::sfu_control::StreamPeerEventsRequest, ::sfu_control::PeerEvent>(
          [](SfuControl::Service* service,
             ::grpc::ServerContext* ctx,
             const ::sfu_control::StreamPeerEventsRequest* req,
             ::grpc::ServerWriter<::sfu_control::PeerEvent>* writer) {
               return service->StreamPeerEvents(ctx, req, writer);
             }, this)));
}

SfuControl::Service::~Service() {
}

::grpc::Status SfuControl::Service::AddPeer(::grpc::ServerContext* context, const ::sfu_control::AddPeerRequest* request, ::sfu_control::AddPeerResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SfuControl::Service::RemovePeer(::grpc::ServerContext* context, const ::sfu_control::RemovePeerRequest* request, ::sfu_control::RemovePeerResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SfuControl::Service::AddRemoteIceCandidate(::grpc::ServerContext* context, const ::sfu_control::AddRemoteIceCandidateRequest* request, ::sfu_control::AddRemoteIceCandidateResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SfuControl::Service::StreamPeerEvents(::grpc::ServerContext* context, const ::sfu_control::StreamPeerEventsRequest* request, ::grpc::ServerWriter< ::sfu_control::PeerEvent>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace sfu_control

