// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sfu_control.proto

#include "sfu_control.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace sfu_control {
PROTOBUF_CONSTEXPR AddPeerRequest::AddPeerRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.room_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.peer_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.offer_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct AddPeerRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AddPeerRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AddPeerRequestDefaultTypeInternal() {}
  union {
    AddPeerRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AddPeerRequestDefaultTypeInternal _AddPeerRequest_default_instance_;
PROTOBUF_CONSTEXPR AddPeerResponse::AddPeerResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.answer_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct AddPeerResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AddPeerResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AddPeerResponseDefaultTypeInternal() {}
  union {
    AddPeerResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AddPeerResponseDefaultTypeInternal _AddPeerResponse_default_instance_;
PROTOBUF_CONSTEXPR RemovePeerRequest::RemovePeerRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.room_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.peer_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct RemovePeerRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RemovePeerRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RemovePeerRequestDefaultTypeInternal() {}
  union {
    RemovePeerRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RemovePeerRequestDefaultTypeInternal _RemovePeerRequest_default_instance_;
PROTOBUF_CONSTEXPR RemovePeerResponse::RemovePeerResponse(
    ::_pbi::ConstantInitialized) {}
struct RemovePeerResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RemovePeerResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RemovePeerResponseDefaultTypeInternal() {}
  union {
    RemovePeerResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RemovePeerResponseDefaultTypeInternal _RemovePeerResponse_default_instance_;
PROTOBUF_CONSTEXPR AddRemoteIceCandidateRequest::AddRemoteIceCandidateRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.room_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.peer_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.candidate_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct AddRemoteIceCandidateRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AddRemoteIceCandidateRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AddRemoteIceCandidateRequestDefaultTypeInternal() {}
  union {
    AddRemoteIceCandidateRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AddRemoteIceCandidateRequestDefaultTypeInternal _AddRemoteIceCandidateRequest_default_instance_;
PROTOBUF_CONSTEXPR AddRemoteIceCandidateResponse::AddRemoteIceCandidateResponse(
    ::_pbi::ConstantInitialized) {}
struct AddRemoteIceCandidateResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AddRemoteIceCandidateResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AddRemoteIceCandidateResponseDefaultTypeInternal() {}
  union {
    AddRemoteIceCandidateResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AddRemoteIceCandidateResponseDefaultTypeInternal _AddRemoteIceCandidateResponse_default_instance_;
PROTOBUF_CONSTEXPR StreamPeerEventsRequest::StreamPeerEventsRequest(
    ::_pbi::ConstantInitialized) {}
struct StreamPeerEventsRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StreamPeerEventsRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~StreamPeerEventsRequestDefaultTypeInternal() {}
  union {
    StreamPeerEventsRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StreamPeerEventsRequestDefaultTypeInternal _StreamPeerEventsRequest_default_instance_;
PROTOBUF_CONSTEXPR PeerEvent::PeerEvent(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.room_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.peer_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.event_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct PeerEventDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PeerEventDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PeerEventDefaultTypeInternal() {}
  union {
    PeerEvent _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PeerEventDefaultTypeInternal _PeerEvent_default_instance_;
}  // namespace sfu_control
static ::_pb::Metadata file_level_metadata_sfu_5fcontrol_2eproto[8];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_sfu_5fcontrol_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_sfu_5fcontrol_2eproto = nullptr;

const uint32_t TableStruct_sfu_5fcontrol_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::sfu_control::AddPeerRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::sfu_control::AddPeerRequest, _impl_.room_id_),
  PROTOBUF_FIELD_OFFSET(::sfu_control::AddPeerRequest, _impl_.peer_id_),
  PROTOBUF_FIELD_OFFSET(::sfu_control::AddPeerRequest, _impl_.offer_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::sfu_control::AddPeerResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::sfu_control::AddPeerResponse, _impl_.answer_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::sfu_control::RemovePeerRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::sfu_control::RemovePeerRequest, _impl_.room_id_),
  PROTOBUF_FIELD_OFFSET(::sfu_control::RemovePeerRequest, _impl_.peer_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::sfu_control::RemovePeerResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::sfu_control::AddRemoteIceCandidateRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::sfu_control::AddRemoteIceCandidateRequest, _impl_.room_id_),
  PROTOBUF_FIELD_OFFSET(::sfu_control::AddRemoteIceCandidateRequest, _impl_.peer_id_),
  PROTOBUF_FIELD_OFFSET(::sfu_control::AddRemoteIceCandidateRequest, _impl_.candidate_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::sfu_control::AddRemoteIceCandidateResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::sfu_control::StreamPeerEventsRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::sfu_control::PeerEvent, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::sfu_control::PeerEvent, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::sfu_control::PeerEvent, _impl_.room_id_),
  PROTOBUF_FIELD_OFFSET(::sfu_control::PeerEvent, _impl_.peer_id_),
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::sfu_control::PeerEvent, _impl_.event_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::sfu_control::AddPeerRequest)},
  { 9, -1, -1, sizeof(::sfu_control::AddPeerResponse)},
  { 16, -1, -1, sizeof(::sfu_control::RemovePeerRequest)},
  { 24, -1, -1, sizeof(::sfu_control::RemovePeerResponse)},
  { 30, -1, -1, sizeof(::sfu_control::AddRemoteIceCandidateRequest)},
  { 39, -1, -1, sizeof(::sfu_control::AddRemoteIceCandidateResponse)},
  { 45, -1, -1, sizeof(::sfu_control::StreamPeerEventsRequest)},
  { 51, -1, -1, sizeof(::sfu_control::PeerEvent)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::sfu_control::_AddPeerRequest_default_instance_._instance,
  &::sfu_control::_AddPeerResponse_default_instance_._instance,
  &::sfu_control::_RemovePeerRequest_default_instance_._instance,
  &::sfu_control::_RemovePeerResponse_default_instance_._instance,
  &::sfu_control::_AddRemoteIceCandidateRequest_default_instance_._instance,
  &::sfu_control::_AddRemoteIceCandidateResponse_default_instance_._instance,
  &::sfu_control::_StreamPeerEventsRequest_default_instance_._instance,
  &::sfu_control::_PeerEvent_default_instance_._instance,
};

const char descriptor_table_protodef_sfu_5fcontrol_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021sfu_control.proto\022\013sfu_control\032\017signal"
  "ing.proto\"Q\n\016AddPeerRequest\022\017\n\007room_id\030\001"
  " \001(\t\022\017\n\007peer_id\030\002 \001(\t\022\035\n\005offer\030\003 \001(\0132\016.s"
  "ignaling.Sdp\"1\n\017AddPeerResponse\022\036\n\006answe"
  "r\030\001 \001(\0132\016.signaling.Sdp\"5\n\021RemovePeerReq"
  "uest\022\017\n\007room_id\030\001 \001(\t\022\017\n\007peer_id\030\002 \001(\t\"\024"
  "\n\022RemovePeerResponse\"l\n\034AddRemoteIceCand"
  "idateRequest\022\017\n\007room_id\030\001 \001(\t\022\017\n\007peer_id"
  "\030\002 \001(\t\022*\n\tcandidate\030\003 \001(\0132\027.signaling.Ic"
  "eCandidate\"\037\n\035AddRemoteIceCandidateRespo"
  "nse\"\031\n\027StreamPeerEventsRequest\"\204\001\n\tPeerE"
  "vent\022\017\n\007room_id\030\001 \001(\t\022\017\n\007peer_id\030\002 \001(\t\0226"
  "\n\023local_ice_candidate\030\003 \001(\0132\027.signaling."
  "IceCandidateH\000\022\024\n\npeer_ready\030\004 \001(\010H\000B\007\n\005"
  "event2\345\002\n\nSfuControl\022D\n\007AddPeer\022\033.sfu_co"
  "ntrol.AddPeerRequest\032\034.sfu_control.AddPe"
  "erResponse\022M\n\nRemovePeer\022\036.sfu_control.R"
  "emovePeerRequest\032\037.sfu_control.RemovePee"
  "rResponse\022n\n\025AddRemoteIceCandidate\022).sfu"
  "_control.AddRemoteIceCandidateRequest\032*."
  "sfu_control.AddRemoteIceCandidateRespons"
  "e\022R\n\020StreamPeerEvents\022$.sfu_control.Stre"
  "amPeerEventsRequest\032\026.sfu_control.PeerEv"
  "ent0\001b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_sfu_5fcontrol_2eproto_deps[1] = {
  &::descriptor_table_signaling_2eproto,
};
static ::_pbi::once_flag descriptor_table_sfu_5fcontrol_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_sfu_5fcontrol_2eproto = {
    false, false, 933, descriptor_table_protodef_sfu_5fcontrol_2eproto,
    "sfu_control.proto",
    &descriptor_table_sfu_5fcontrol_2eproto_once, descriptor_table_sfu_5fcontrol_2eproto_deps, 1, 8,
    schemas, file_default_instances, TableStruct_sfu_5fcontrol_2eproto::offsets,
    file_level_metadata_sfu_5fcontrol_2eproto, file_level_enum_descriptors_sfu_5fcontrol_2eproto,
    file_level_service_descriptors_sfu_5fcontrol_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_sfu_5fcontrol_2eproto_getter() {
  return &descriptor_table_sfu_5fcontrol_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_sfu_5fcontrol_2eproto(&descriptor_table_sfu_5fcontrol_2eproto);
namespace sfu_control {

// ===================================================================

class AddPeerRequest::_Internal {
 public:
  static const ::signaling::Sdp& offer(const AddPeerRequest* msg);
};

const ::signaling::Sdp&
AddPeerRequest::_Internal::offer(const AddPeerRequest* msg) {
  return *msg->_impl_.offer_;
}
void AddPeerRequest::clear_offer() {
  if (GetArenaForAllocation() == nullptr && _impl_.offer_ != nullptr) {
    delete _impl_.offer_;
  }
  _impl_.offer_ = nullptr;
}
AddPeerRequest::AddPeerRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:sfu_control.AddPeerRequest)
}
AddPeerRequest::AddPeerRequest(const AddPeerRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AddPeerRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.room_id_){}
    , decltype(_impl_.peer_id_){}
    , decltype(_impl_.offer_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.room_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.room_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_room_id().empty()) {
    _this->_impl_.room_id_.Set(from._internal_room_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.peer_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.peer_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_peer_id().empty()) {
    _this->_impl_.peer_id_.Set(from._internal_peer_id(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_offer()) {
    _this->_impl_.offer_ = new ::signaling::Sdp(*from._impl_.offer_);
  }
  // @@protoc_insertion_point(copy_constructor:sfu_control.AddPeerRequest)
}

inline void AddPeerRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.room_id_){}
    , decltype(_impl_.peer_id_){}
    , decltype(_impl_.offer_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.room_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.room_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.peer_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.peer_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

AddPeerRequest::~AddPeerRequest() {
  // @@protoc_insertion_point(destructor:sfu_control.AddPeerRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AddPeerRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.room_id_.Destroy();
  _impl_.peer_id_.Destroy();
  if (this != internal_default_instance()) delete _impl_.offer_;
}

void AddPeerRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AddPeerRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:sfu_control.AddPeerRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.room_id_.ClearToEmpty();
  _impl_.peer_id_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.offer_ != nullptr) {
    delete _impl_.offer_;
  }
  _impl_.offer_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AddPeerRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string room_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_room_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "sfu_control.AddPeerRequest.room_id"));
        } else
          goto handle_unusual;
        continue;
      // string peer_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_peer_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "sfu_control.AddPeerRequest.peer_id"));
        } else
          goto handle_unusual;
        continue;
      // .signaling.Sdp offer = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_offer(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* AddPeerRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sfu_control.AddPeerRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string room_id = 1;
  if (!this->_internal_room_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_room_id().data(), static_cast<int>(this->_internal_room_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "sfu_control.AddPeerRequest.room_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_room_id(), target);
  }

  // string peer_id = 2;
  if (!this->_internal_peer_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_peer_id().data(), static_cast<int>(this->_internal_peer_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "sfu_control.AddPeerRequest.peer_id");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_peer_id(), target);
  }

  // .signaling.Sdp offer = 3;
  if (this->_internal_has_offer()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::offer(this),
        _Internal::offer(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sfu_control.AddPeerRequest)
  return target;
}

size_t AddPeerRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sfu_control.AddPeerRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string room_id = 1;
  if (!this->_internal_room_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_room_id());
  }

  // string peer_id = 2;
  if (!this->_internal_peer_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_peer_id());
  }

  // .signaling.Sdp offer = 3;
  if (this->_internal_has_offer()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.offer_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AddPeerRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AddPeerRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AddPeerRequest::GetClassData() const { return &_class_data_; }


void AddPeerRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AddPeerRequest*>(&to_msg);
  auto& from = static_cast<const AddPeerRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sfu_control.AddPeerRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_room_id().empty()) {
    _this->_internal_set_room_id(from._internal_room_id());
  }
  if (!from._internal_peer_id().empty()) {
    _this->_internal_set_peer_id(from._internal_peer_id());
  }
  if (from._internal_has_offer()) {
    _this->_internal_mutable_offer()->::signaling::Sdp::MergeFrom(
        from._internal_offer());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AddPeerRequest::CopyFrom(const AddPeerRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sfu_control.AddPeerRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AddPeerRequest::IsInitialized() const {
  return true;
}

void AddPeerRequest::InternalSwap(AddPeerRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.room_id_, lhs_arena,
      &other->_impl_.room_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.peer_id_, lhs_arena,
      &other->_impl_.peer_id_, rhs_arena
  );
  swap(_impl_.offer_, other->_impl_.offer_);
}

::PROTOBUF_NAMESPACE_ID::Metadata AddPeerRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_sfu_5fcontrol_2eproto_getter, &descriptor_table_sfu_5fcontrol_2eproto_once,
      file_level_metadata_sfu_5fcontrol_2eproto[0]);
}

// ===================================================================

class AddPeerResponse::_Internal {
 public:
  static const ::signaling::Sdp& answer(const AddPeerResponse* msg);
};

const ::signaling::Sdp&
AddPeerResponse::_Internal::answer(const AddPeerResponse* msg) {
  return *msg->_impl_.answer_;
}
void AddPeerResponse::clear_answer() {
  if (GetArenaForAllocation() == nullptr && _impl_.answer_ != nullptr) {
    delete _impl_.answer_;
  }
  _impl_.answer_ = nullptr;
}
AddPeerResponse::AddPeerResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:sfu_control.AddPeerResponse)
}
AddPeerResponse::AddPeerResponse(const AddPeerResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AddPeerResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.answer_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_answer()) {
    _this->_impl_.answer_ = new ::signaling::Sdp(*from._impl_.answer_);
  }
  // @@protoc_insertion_point(copy_constructor:sfu_control.AddPeerResponse)
}

inline void AddPeerResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.answer_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

AddPeerResponse::~AddPeerResponse() {
  // @@protoc_insertion_point(destructor:sfu_control.AddPeerResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AddPeerResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.answer_;
}

void AddPeerResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AddPeerResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:sfu_control.AddPeerResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.answer_ != nullptr) {
    delete _impl_.answer_;
  }
  _impl_.answer_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AddPeerResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .signaling.Sdp answer = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_answer(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* AddPeerResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sfu_control.AddPeerResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .signaling.Sdp answer = 1;
  if (this->_internal_has_answer()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::answer(this),
        _Internal::answer(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sfu_control.AddPeerResponse)
  return target;
}

size_t AddPeerResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sfu_control.AddPeerResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .signaling.Sdp answer = 1;
  if (this->_internal_has_answer()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.answer_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AddPeerResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AddPeerResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AddPeerResponse::GetClassData() const { return &_class_data_; }


void AddPeerResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AddPeerResponse*>(&to_msg);
  auto& from = static_cast<const AddPeerResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sfu_control.AddPeerResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_answer()) {
    _this->_internal_mutable_answer()->::signaling::Sdp::MergeFrom(
        from._internal_answer());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AddPeerResponse::CopyFrom(const AddPeerResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sfu_control.AddPeerResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AddPeerResponse::IsInitialized() const {
  return true;
}

void AddPeerResponse::InternalSwap(AddPeerResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.answer_, other->_impl_.answer_);
}

::PROTOBUF_NAMESPACE_ID::Metadata AddPeerResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_sfu_5fcontrol_2eproto_getter, &descriptor_table_sfu_5fcontrol_2eproto_once,
      file_level_metadata_sfu_5fcontrol_2eproto[1]);
}

// ===================================================================

class RemovePeerRequest::_Internal {
 public:
};

RemovePeerRequest::RemovePeerRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:sfu_control.RemovePeerRequest)
}
RemovePeerRequest::RemovePeerRequest(const RemovePeerRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RemovePeerRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.room_id_){}
    , decltype(_impl_.peer_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.room_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.room_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_room_id().empty()) {
    _this->_impl_.room_id_.Set(from._internal_room_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.peer_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.peer_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_peer_id().empty()) {
    _this->_impl_.peer_id_.Set(from._internal_peer_id(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:sfu_control.RemovePeerRequest)
}

inline void RemovePeerRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.room_id_){}
    , decltype(_impl_.peer_id_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.room_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.room_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.peer_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.peer_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

RemovePeerRequest::~RemovePeerRequest() {
  // @@protoc_insertion_point(destructor:sfu_control.RemovePeerRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RemovePeerRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.room_id_.Destroy();
  _impl_.peer_id_.Destroy();
}

void RemovePeerRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RemovePeerRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:sfu_control.RemovePeerRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.room_id_.ClearToEmpty();
  _impl_.peer_id_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RemovePeerRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string room_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_room_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "sfu_control.RemovePeerRequest.room_id"));
        } else
          goto handle_unusual;
        continue;
      // string peer_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_peer_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "sfu_control.RemovePeerRequest.peer_id"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RemovePeerRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sfu_control.RemovePeerRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string room_id = 1;
  if (!this->_internal_room_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_room_id().data(), static_cast<int>(this->_internal_room_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "sfu_control.RemovePeerRequest.room_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_room_id(), target);
  }

  // string peer_id = 2;
  if (!this->_internal_peer_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_peer_id().data(), static_cast<int>(this->_internal_peer_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "sfu_control.RemovePeerRequest.peer_id");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_peer_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sfu_control.RemovePeerRequest)
  return target;
}

size_t RemovePeerRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sfu_control.RemovePeerRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string room_id = 1;
  if (!this->_internal_room_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_room_id());
  }

  // string peer_id = 2;
  if (!this->_internal_peer_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_peer_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RemovePeerRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RemovePeerRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RemovePeerRequest::GetClassData() const { return &_class_data_; }


void RemovePeerRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RemovePeerRequest*>(&to_msg);
  auto& from = static_cast<const RemovePeerRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sfu_control.RemovePeerRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_room_id().empty()) {
    _this->_internal_set_room_id(from._internal_room_id());
  }
  if (!from._internal_peer_id().empty()) {
    _this->_internal_set_peer_id(from._internal_peer_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RemovePeerRequest::CopyFrom(const RemovePeerRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sfu_control.RemovePeerRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RemovePeerRequest::IsInitialized() const {
  return true;
}

void RemovePeerRequest::InternalSwap(RemovePeerRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.room_id_, lhs_arena,
      &other->_impl_.room_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.peer_id_, lhs_arena,
      &other->_impl_.peer_id_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata RemovePeerRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_sfu_5fcontrol_2eproto_getter, &descriptor_table_sfu_5fcontrol_2eproto_once,
      file_level_metadata_sfu_5fcontrol_2eproto[2]);
}

// ===================================================================

class RemovePeerResponse::_Internal {
 public:
};

RemovePeerResponse::RemovePeerResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:sfu_control.RemovePeerResponse)
}
RemovePeerResponse::RemovePeerResponse(const RemovePeerResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  RemovePeerResponse* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:sfu_control.RemovePeerResponse)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RemovePeerResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RemovePeerResponse::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata RemovePeerResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_sfu_5fcontrol_2eproto_getter, &descriptor_table_sfu_5fcontrol_2eproto_once,
      file_level_metadata_sfu_5fcontrol_2eproto[3]);
}

// ===================================================================

class AddRemoteIceCandidateRequest::_Internal {
 public:
  static const ::signaling::IceCandidate& candidate(const AddRemoteIceCandidateRequest* msg);
};

const ::signaling::IceCandidate&
AddRemoteIceCandidateRequest::_Internal::candidate(const AddRemoteIceCandidateRequest* msg) {
  return *msg->_impl_.candidate_;
}
void AddRemoteIceCandidateRequest::clear_candidate() {
  if (GetArenaForAllocation() == nullptr && _impl_.candidate_ != nullptr) {
    delete _impl_.candidate_;
  }
  _impl_.candidate_ = nullptr;
}
AddRemoteIceCandidateRequest::AddRemoteIceCandidateRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:sfu_control.AddRemoteIceCandidateRequest)
}
AddRemoteIceCandidateRequest::AddRemoteIceCandidateRequest(const AddRemoteIceCandidateRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AddRemoteIceCandidateRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.room_id_){}
    , decltype(_impl_.peer_id_){}
    , decltype(_impl_.candidate_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.room_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.room_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_room_id().empty()) {
    _this->_impl_.room_id_.Set(from._internal_room_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.peer_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.peer_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_peer_id().empty()) {
    _this->_impl_.peer_id_.Set(from._internal_peer_id(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_candidate()) {
    _this->_impl_.candidate_ = new ::signaling::IceCandidate(*from._impl_.candidate_);
  }
  // @@protoc_insertion_point(copy_constructor:sfu_control.AddRemoteIceCandidateRequest)
}

inline void AddRemoteIceCandidateRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.room_id_){}
    , decltype(_impl_.peer_id_){}
    , decltype(_impl_.candidate_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.room_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.room_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.peer_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.peer_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

AddRemoteIceCandidateRequest::~AddRemoteIceCandidateRequest() {
  // @@protoc_insertion_point(destructor:sfu_control.AddRemoteIceCandidateRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AddRemoteIceCandidateRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.room_id_.Destroy();
  _impl_.peer_id_.Destroy();
  if (this != internal_default_instance()) delete _impl_.candidate_;
}

void AddRemoteIceCandidateRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AddRemoteIceCandidateRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:sfu_control.AddRemoteIceCandidateRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.room_id_.ClearToEmpty();
  _impl_.peer_id_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.candidate_ != nullptr) {
    delete _impl_.candidate_;
  }
  _impl_.candidate_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AddRemoteIceCandidateRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string room_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_room_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "sfu_control.AddRemoteIceCandidateRequest.room_id"));
        } else
          goto handle_unusual;
        continue;
      // string peer_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_peer_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "sfu_control.AddRemoteIceCandidateRequest.peer_id"));
        } else
          goto handle_unusual;
        continue;
      // .signaling.IceCandidate candidate = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_candidate(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* AddRemoteIceCandidateRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sfu_control.AddRemoteIceCandidateRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string room_id = 1;
  if (!this->_internal_room_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_room_id().data(), static_cast<int>(this->_internal_room_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "sfu_control.AddRemoteIceCandidateRequest.room_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_room_id(), target);
  }

  // string peer_id = 2;
  if (!this->_internal_peer_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_peer_id().data(), static_cast<int>(this->_internal_peer_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "sfu_control.AddRemoteIceCandidateRequest.peer_id");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_peer_id(), target);
  }

  // .signaling.IceCandidate candidate = 3;
  if (this->_internal_has_candidate()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::candidate(this),
        _Internal::candidate(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sfu_control.AddRemoteIceCandidateRequest)
  return target;
}

size_t AddRemoteIceCandidateRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sfu_control.AddRemoteIceCandidateRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string room_id = 1;
  if (!this->_internal_room_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_room_id());
  }

  // string peer_id = 2;
  if (!this->_internal_peer_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_peer_id());
  }

  // .signaling.IceCandidate candidate = 3;
  if (this->_internal_has_candidate()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.candidate_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AddRemoteIceCandidateRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AddRemoteIceCandidateRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AddRemoteIceCandidateRequest::GetClassData() const { return &_class_data_; }


void AddRemoteIceCandidateRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AddRemoteIceCandidateRequest*>(&to_msg);
  auto& from = static_cast<const AddRemoteIceCandidateRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sfu_control.AddRemoteIceCandidateRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_room_id().empty()) {
    _this->_internal_set_room_id(from._internal_room_id());
  }
  if (!from._internal_peer_id().empty()) {
    _this->_internal_set_peer_id(from._internal_peer_id());
  }
  if (from._internal_has_candidate()) {
    _this->_internal_mutable_candidate()->::signaling::IceCandidate::MergeFrom(
        from._internal_candidate());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AddRemoteIceCandidateRequest::CopyFrom(const AddRemoteIceCandidateRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sfu_control.AddRemoteIceCandidateRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AddRemoteIceCandidateRequest::IsInitialized() const {
  return true;
}

void AddRemoteIceCandidateRequest::InternalSwap(AddRemoteIceCandidateRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.room_id_, lhs_arena,
      &other->_impl_.room_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.peer_id_, lhs_arena,
      &other->_impl_.peer_id_, rhs_arena
  );
  swap(_impl_.candidate_, other->_impl_.candidate_);
}

::PROTOBUF_NAMESPACE_ID::Metadata AddRemoteIceCandidateRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_sfu_5fcontrol_2eproto_getter, &descriptor_table_sfu_5fcontrol_2eproto_once,
      file_level_metadata_sfu_5fcontrol_2eproto[4]);
}

// ===================================================================

class AddRemoteIceCandidateResponse::_Internal {
 public:
};

AddRemoteIceCandidateResponse::AddRemoteIceCandidateResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:sfu_control.AddRemoteIceCandidateResponse)
}
AddRemoteIceCandidateResponse::AddRemoteIceCandidateResponse(const AddRemoteIceCandidateResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  AddRemoteIceCandidateResponse* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:sfu_control.AddRemoteIceCandidateResponse)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AddRemoteIceCandidateResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AddRemoteIceCandidateResponse::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata AddRemoteIceCandidateResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_sfu_5fcontrol_2eproto_getter, &descriptor_table_sfu_5fcontrol_2eproto_once,
      file_level_metadata_sfu_5fcontrol_2eproto[5]);
}

// ===================================================================

class StreamPeerEventsRequest::_Internal {
 public:
};

StreamPeerEventsRequest::StreamPeerEventsRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:sfu_control.StreamPeerEventsRequest)
}
StreamPeerEventsRequest::StreamPeerEventsRequest(const StreamPeerEventsRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  StreamPeerEventsRequest* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:sfu_control.StreamPeerEventsRequest)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData StreamPeerEventsRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*StreamPeerEventsRequest::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata StreamPeerEventsRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_sfu_5fcontrol_2eproto_getter, &descriptor_table_sfu_5fcontrol_2eproto_once,
      file_level_metadata_sfu_5fcontrol_2eproto[6]);
}

// ===================================================================

class PeerEvent::_Internal {
 public:
  static const ::signaling::IceCandidate& local_ice_candidate(const PeerEvent* msg);
};

const ::signaling::IceCandidate&
PeerEvent::_Internal::local_ice_candidate(const PeerEvent* msg) {
  return *msg->_impl_.event_.local_ice_candidate_;
}
void PeerEvent::set_allocated_local_ice_candidate(::signaling::IceCandidate* local_ice_candidate) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_event();
  if (local_ice_candidate) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(local_ice_candidate));
    if (message_arena != submessage_arena) {
      local_ice_candidate = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, local_ice_candidate, submessage_arena);
    }
    set_has_local_ice_candidate();
    _impl_.event_.local_ice_candidate_ = local_ice_candidate;
  }
  // @@protoc_insertion_point(field_set_allocated:sfu_control.PeerEvent.local_ice_candidate)
}
void PeerEvent::clear_local_ice_candidate() {
  if (_internal_has_local_ice_candidate()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.event_.local_ice_candidate_;
    }
    clear_has_event();
  }
}
PeerEvent::PeerEvent(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:sfu_control.PeerEvent)
}
PeerEvent::PeerEvent(const PeerEvent& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PeerEvent* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.room_id_){}
    , decltype(_impl_.peer_id_){}
    , decltype(_impl_.event_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.room_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.room_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_room_id().empty()) {
    _this->_impl_.room_id_.Set(from._internal_room_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.peer_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.peer_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_peer_id().empty()) {
    _this->_impl_.peer_id_.Set(from._internal_peer_id(), 
      _this->GetArenaForAllocation());
  }
  clear_has_event();
  switch (from.event_case()) {
    case kLocalIceCandidate: {
      _this->_internal_mutable_local_ice_candidate()->::signaling::IceCandidate::MergeFrom(
          from._internal_local_ice_candidate());
      break;
    }
    case kPeerReady: {
      _this->_internal_set_peer_ready(from._internal_peer_ready());
      break;
    }
    case EVENT_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:sfu_control.PeerEvent)
}

inline void PeerEvent::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.room_id_){}
    , decltype(_impl_.peer_id_){}
    , decltype(_impl_.event_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  _impl_.room_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.room_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.peer_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.peer_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  clear_has_event();
}

PeerEvent::~PeerEvent() {
  // @@protoc_insertion_point(destructor:sfu_control.PeerEvent)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PeerEvent::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.room_id_.Destroy();
  _impl_.peer_id_.Destroy();
  if (has_event()) {
    clear_event();
  }
}

void PeerEvent::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PeerEvent::clear_event() {
// @@protoc_insertion_point(one_of_clear_start:sfu_control.PeerEvent)
  switch (event_case()) {
    case kLocalIceCandidate: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.event_.local_ice_candidate_;
      }
      break;
    }
    case kPeerReady: {
      // No need to clear
      break;
    }
    case EVENT_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = EVENT_NOT_SET;
}


void PeerEvent::Clear() {
// @@protoc_insertion_point(message_clear_start:sfu_control.PeerEvent)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.room_id_.ClearToEmpty();
  _impl_.peer_id_.ClearToEmpty();
  clear_event();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PeerEvent::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string room_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_room_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "sfu_control.PeerEvent.room_id"));
        } else
          goto handle_unusual;
        continue;
      // string peer_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_peer_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "sfu_control.PeerEvent.peer_id"));
        } else
          goto handle_unusual;
        continue;
      // .signaling.IceCandidate local_ice_candidate = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_local_ice_candidate(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool peer_ready = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _internal_set_peer_ready(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PeerEvent::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sfu_control.PeerEvent)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string room_id = 1;
  if (!this->_internal_room_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_room_id().data(), static_cast<int>(this->_internal_room_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "sfu_control.PeerEvent.room_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_room_id(), target);
  }

  // string peer_id = 2;
  if (!this->_internal_peer_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_peer_id().data(), static_cast<int>(this->_internal_peer_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "sfu_control.PeerEvent.peer_id");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_peer_id(), target);
  }

  // .signaling.IceCandidate local_ice_candidate = 3;
  if (_internal_has_local_ice_candidate()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::local_ice_candidate(this),
        _Internal::local_ice_candidate(this).GetCachedSize(), target, stream);
  }

  // bool peer_ready = 4;
  if (_internal_has_peer_ready()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(4, this->_internal_peer_ready(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sfu_control.PeerEvent)
  return target;
}

size_t PeerEvent::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sfu_control.PeerEvent)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string room_id = 1;
  if (!this->_internal_room_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_room_id());
  }

  // string peer_id = 2;
  if (!this->_internal_peer_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_peer_id());
  }

  switch (event_case()) {
    // .signaling.IceCandidate local_ice_candidate = 3;
    case kLocalIceCandidate: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.event_.local_ice_candidate_);
      break;
    }
    // bool peer_ready = 4;
    case kPeerReady: {
      total_size += 1 + 1;
      break;
    }
    case EVENT_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PeerEvent::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PeerEvent::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PeerEvent::GetClassData() const { return &_class_data_; }


void PeerEvent::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PeerEvent*>(&to_msg);
  auto& from = static_cast<const PeerEvent&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sfu_control.PeerEvent)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_room_id().empty()) {
    _this->_internal_set_room_id(from._internal_room_id());
  }
  if (!from._internal_peer_id().empty()) {
    _this->_internal_set_peer_id(from._internal_peer_id());
  }
  switch (from.event_case()) {
    case kLocalIceCandidate: {
      _this->_internal_mutable_local_ice_candidate()->::signaling::IceCandidate::MergeFrom(
          from._internal_local_ice_candidate());
      break;
    }
    case kPeerReady: {
      _this->_internal_set_peer_ready(from._internal_peer_ready());
      break;
    }
    case EVENT_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PeerEvent::CopyFrom(const PeerEvent& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sfu_control.PeerEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PeerEvent::IsInitialized() const {
  return true;
}

void PeerEvent::InternalSwap(PeerEvent* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.room_id_, lhs_arena,
      &other->_impl_.room_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.peer_id_, lhs_arena,
      &other->_impl_.peer_id_, rhs_arena
  );
  swap(_impl_.event_, other->_impl_.event_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata PeerEvent::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_sfu_5fcontrol_2eproto_getter, &descriptor_table_sfu_5fcontrol_2eproto_once,
      file_level_metadata_sfu_5fcontrol_2eproto[7]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace sfu_control
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::sfu_control::AddPeerRequest*
Arena::CreateMaybeMessage< ::sfu_control::AddPeerRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sfu_control::AddPeerRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::sfu_control::AddPeerResponse*
Arena::CreateMaybeMessage< ::sfu_control::AddPeerResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sfu_control::AddPeerResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::sfu_control::RemovePeerRequest*
Arena::CreateMaybeMessage< ::sfu_control::RemovePeerRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sfu_control::RemovePeerRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::sfu_control::RemovePeerResponse*
Arena::CreateMaybeMessage< ::sfu_control::RemovePeerResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sfu_control::RemovePeerResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::sfu_control::AddRemoteIceCandidateRequest*
Arena::CreateMaybeMessage< ::sfu_control::AddRemoteIceCandidateRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sfu_control::AddRemoteIceCandidateRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::sfu_control::AddRemoteIceCandidateResponse*
Arena::CreateMaybeMessage< ::sfu_control::AddRemoteIceCandidateResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sfu_control::AddRemoteIceCandidateResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::sfu_control::StreamPeerEventsRequest*
Arena::CreateMaybeMessage< ::sfu_control::StreamPeerEventsRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sfu_control::StreamPeerEventsRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::sfu_control::PeerEvent*
Arena::CreateMaybeMessage< ::sfu_control::PeerEvent >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sfu_control::PeerEvent >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
